<?php
require_once __DIR__.'/../../Other/core/website-runtime.php';
// Validates avatar+password against the Robust DB (same UserAccounts/auth join and
// md5(md5(password):salt) check as GetAvatarLoginLevel in Modules/Mysql.vb) and, on
// success, sets a cookie so other pages under /API can read who is logged in without
// re-sending the password. config.php is generated by DreamGrid's DoPhpDbSetup() and
// is kept in sync with Settings.RobustMysqlConnection, so it's safe to trust as the
// DB connection source of truth.
require_once __DIR__ . '/../../MetroMap/includes/config.php';

header('Content-Type: text/plain');

$avatar = trim($_POST['avatar'] ?? '');
$password = (string) ($_POST['password'] ?? '');

$parts = preg_split('/\s+/', $avatar, 2);
$firstName = $parts[0] ?? '';
$lastName = $parts[1] ?? '';

if ($firstName === '' || $lastName === '') {
    echo 'NAK You do not have permission to Log In';
    exit;
}

$con = mysqli_connect($CONF_db_server, $CONF_db_user, $CONF_db_pass, $CONF_db_database, (int) $CONF_db_port);
if (!$con) {
    echo 'NAK You do not have permission to Log In';
    exit;
}

$stmt = mysqli_prepare($con, 'SELECT ua.UserLevel, ua.PrincipalID, a.passwordHash, a.passwordSalt
FROM UserAccounts ua
INNER JOIN auth a ON ua.PrincipalID = a.UUID
WHERE ua.FirstName = ? AND ua.LastName = ?');
mysqli_stmt_bind_param($stmt, 'ss', $firstName, $lastName);
mysqli_stmt_execute($stmt);
mysqli_stmt_bind_result($stmt, $userLevel, $principalId, $passwordHash, $passwordSalt);

$found = mysqli_stmt_fetch($stmt);
mysqli_stmt_close($stmt);
mysqli_close($con);

if (!$found) {
    echo 'NAK You do not have permission to Log In';
    exit;
}

// Same two-stage MD5 as GetMD5 in Modules/Mysql.vb: md5(password) then md5("{that}:{salt}")
$hashed = md5(md5($password) . ':' . $passwordSalt);

if ($hashed !== $passwordHash || $userLevel < 0) {
    echo 'NAK You do not have permission to Log In';
    exit;
}

$session = [
    'avatar' => "$firstName $lastName",
    'principalId' => $principalId,
    'level' => (int) $userLevel,
];

// Cookie is the session's own trust boundary: signed with a server-side secret so a
// client can't forge a higher UserLevel by editing the cookie value directly.
$secret = dreamGridSessionSecret();
$payload = base64_encode(json_encode($session));
$signature = hash_hmac('sha256', $payload, $secret);
setcookie('dg_session', "$payload.$signature", [
    'expires' => time() + 8 * 3600,
    'path' => '/API/',
    'httponly' => true,
    'secure' => ag_web_secure_request(),
    'samesite' => 'Lax',
]);

echo 'Success';

function dreamGridSessionSecret() {
    $keyFile = __DIR__ . '/session_secret.php';
    if (!file_exists($keyFile)) {
        $key = bin2hex(random_bytes(32));
        file_put_contents($keyFile, "<?php\nreturn " . var_export($key, true) . ";\n");
    }
    return include $keyFile;
}
