<?php

declare(strict_types=1);
require_once __DIR__.'/website-runtime.php';


/*
 * Region database helper.
 *
 * Reads the generated region database connection from:
 *
 *   [HoloPhysicsGuard]
 *   ConnectionString = ...
 *
 * The connection string is generated by the native grid manager
 * from its own region database settings.
 *
 * Credentials are never displayed or logged here.
 */


function ag_region_db_connection_value(
    string $connectionString,
    array $keys
): ?string {

    foreach ($keys as $key) {

        $pattern =
            '/(?:^|;)\s*' .
            preg_quote($key, '/') .
            '\s*=\s*([^;]*)/i';

        if (
            preg_match(
                $pattern,
                $connectionString,
                $match
            )
        ) {

            return trim(
                $match[1],
                " \t\n\r\0\x0B\""
            );
        }
    }

    return null;
}


function ag_region_db_config(): ?array
{
    static $loaded =
        false;

    static $cached =
        null;

    if ($loaded) {
        return $cached;
    }

    $loaded =
        true;

    $regionsRoot =
        ag_dg_regions_root();

    if (
        !is_dir($regionsRoot)
    ) {
        return null;
    }

    try {

        $iterator =
            new RecursiveIteratorIterator(
                new RecursiveDirectoryIterator(
                    $regionsRoot,
                    FilesystemIterator::SKIP_DOTS
                )
            );

        foreach ($iterator as $file) {

            if (
                !$file->isFile() ||
                strcasecmp(
                    $file->getFilename(),
                    'Opensim.ini'
                ) !== 0
            ) {
                continue;
            }

            $lines =
                @file(
                    $file->getPathname(),
                    FILE_IGNORE_NEW_LINES
                );

            if (
                !is_array($lines)
            ) {
                continue;
            }

            $section =
                '';

            foreach ($lines as $line) {

                if (
                    preg_match(
                        '/^\s*\[([^\]]+)\]\s*$/',
                        $line,
                        $sectionMatch
                    )
                ) {

                    $section =
                        trim(
                            $sectionMatch[1]
                        );

                    continue;
                }

                if (
                    strcasecmp(
                        $section,
                        'HoloPhysicsGuard'
                    ) !== 0
                ) {
                    continue;
                }

                if (
                    !preg_match(
                        '/^\s*ConnectionString\s*=\s*(.+?)\s*$/i',
                        $line,
                        $connectionMatch
                    )
                ) {
                    continue;
                }

                $connectionString =
                    trim(
                        $connectionMatch[1]
                    );

                if (
                    strlen($connectionString) >= 2 &&
                    $connectionString[0] === '"' &&
                    substr(
                        $connectionString,
                        -1
                    ) === '"'
                ) {

                    $connectionString =
                        substr(
                            $connectionString,
                            1,
                            -1
                        );
                }

                $host =
                    ag_region_db_connection_value(
                        $connectionString,
                        [
                            'Data Source',
                            'Server',
                            'Host'
                        ]
                    );

                $database =
                    ag_region_db_connection_value(
                        $connectionString,
                        [
                            'Database',
                            'Initial Catalog'
                        ]
                    );

                $port =
                    ag_region_db_connection_value(
                        $connectionString,
                        [
                            'Port'
                        ]
                    );

                $user =
                    ag_region_db_connection_value(
                        $connectionString,
                        [
                            'User ID',
                            'User',
                            'UID'
                        ]
                    );

                $password =
                    ag_region_db_connection_value(
                        $connectionString,
                        [
                            'Password',
                            'Pwd'
                        ]
                    );

                if (
                    $host === null ||
                    $host === '' ||
                    $database === null ||
                    $database === '' ||
                    $user === null ||
                    $password === null
                ) {
                    continue;
                }

                $cached = [
                    'host' =>
                        $host,

                    'database' =>
                        $database,

                    'port' =>
                        (
                            is_numeric($port)
                                ? (int)$port
                                : ag_web_database_port('region')
                        ),

                    'user' =>
                        $user,

                    'password' =>
                        $password,
                ];

                return $cached;
            }
        }

    }
    catch (Throwable $e) {

        return null;
    }

    return null;
}


function ag_region_db_connect(): ?mysqli
{
    if (
        !function_exists(
            'mysqli_init'
        )
    ) {
        return null;
    }

    $config =
        ag_region_db_config();

    if (
        $config === null
    ) {
        return null;
    }

    $db =
        null;

    try {

        $db =
            mysqli_init();

        if (!$db) {
            return null;
        }

        @mysqli_options(
            $db,
            MYSQLI_OPT_CONNECT_TIMEOUT,
            3
        );

        $connected =
            @mysqli_real_connect(
                $db,
                $config['host'],
                $config['user'],
                $config['password'],
                $config['database'],
                $config['port']
            );

        if (!$connected) {

            @mysqli_close(
                $db
            );

            return null;
        }

        @mysqli_set_charset(
            $db,
            'utf8mb4'
        );

        return $db;
    }
    catch (Throwable $e) {

        if (
            $db instanceof mysqli
        ) {

            try {
                $db->close();
            }
            catch (Throwable $ignored) {
            }
        }

        return null;
    }
}


function ag_region_parcel_settings(
    ?mysqli $db,
    string $regionUuid
): string {

    if (
        $db === null ||
        !preg_match(
            '/^[0-9a-fA-F]{8}-' .
            '[0-9a-fA-F]{4}-' .
            '[0-9a-fA-F]{4}-' .
            '[0-9a-fA-F]{4}-' .
            '[0-9a-fA-F]{12}$/',
            $regionUuid
        )
    ) {
        return '-';
    }

    $statement =
        null;

    try {

        $statement =
            $db->prepare(
                'SELECT name, landflags ' .
                'FROM land ' .
                'WHERE regionuuid = ? ' .
                'AND ((landflags & 64) OR (landflags & 16))'
            );

        if (!$statement) {
            return '-';
        }

        $statement->bind_param(
            's',
            $regionUuid
        );

        if (
            !$statement->execute()
        ) {
            return '-';
        }

        $parcelName =
            '';

        $parcelFlags =
            0;

        $statement->bind_result(
            $parcelName,
            $parcelFlags
        );

        /*
         * Native behavior reads only the first matching row.
         */

        if (
            !$statement->fetch()
        ) {
            return '-';
        }

        $parcelFlags =
            (int)$parcelFlags;

        $value =
            (string)$parcelName .
            ' (';

        if (
            ($parcelFlags & 64) !== 0
        ) {
            $value .=
                'Build ';
        }

        if (
            ($parcelFlags & 16) !== 0
        ) {
            $value .=
                'Land ';
        }

        $value .=
            ')';

        return $value;
    }
    catch (Throwable $e) {

        return '-';
    }
    finally {

        if (
            $statement instanceof mysqli_stmt
        ) {

            try {
                $statement->close();
            }
            catch (Throwable $ignored) {
            }
        }
    }
}