(() => {
    'use strict';
    const cfg=JSON.parse(document.getElementById('design-config').textContent),preview=document.getElementById('theme-preview'),frame=document.getElementById('preview-frame'),area=document.getElementById('preview-area'),editor=document.getElementById('theme-editor'),form=document.getElementById('theme-edit-form'),live=document.getElementById('editor-frame'),editArea=document.getElementById('editor-area');
    document.querySelectorAll('.open-apply').forEach(button=>button.addEventListener('click',()=>{const details=button.closest('article').querySelector('.apply-options');details.open=true;details.scrollIntoView({block:'nearest',behavior:'smooth'});}));
    const artFilter=document.getElementById('artwork-filter');if(artFilter)artFilter.addEventListener('change',()=>{document.querySelectorAll('[data-art-category]').forEach(card=>card.hidden=artFilter.value!=='all'&&card.dataset.artCategory!==artFilter.value);document.querySelector('[data-library=builtins]').hidden=artFilter.value==='uploads';document.querySelector('[data-library=uploads]').hidden=!['all','uploads'].includes(artFilter.value);});
    let theme='current',fixed='',backgroundBlob='',editorOriginal=null;
    const field=name=>name==='action'?form.querySelector('input[name=action]'):form.elements.namedItem(name);
    function showPreview(){document.getElementById('preview-customize').disabled=theme==='current';frame.src=fixed||'/Other/site-theme-preview.php?scope='+encodeURIComponent(area.value)+'&theme='+encodeURIComponent(theme);}
    document.querySelectorAll('.preview-theme').forEach(button=>button.addEventListener('click',()=>{theme=button.dataset.theme;fixed='';area.disabled=false;document.getElementById('preview-actions').hidden=false;showPreview();preview.showModal();}));
    document.querySelectorAll('.preview-design').forEach(button=>button.addEventListener('click',()=>{fixed=button.dataset.url;const scope=new URL(fixed,location.origin).searchParams.get('scope')||'public';area.value=[...area.options].some(o=>o.value===scope)?scope:'public';area.disabled=true;document.getElementById('preview-actions').hidden=true;showPreview();preview.showModal();}));
    area.addEventListener('change',showPreview);
    document.querySelectorAll('[data-close]').forEach(button=>button.addEventListener('click',()=>document.getElementById(button.dataset.close).close()));
    preview.addEventListener('close',()=>{frame.src='about:blank';});
    document.querySelectorAll('.preview-device').forEach(select=>select.addEventListener('change',()=>document.getElementById(select.dataset.frame).classList.toggle('mobile',select.value==='mobile')));
    document.querySelectorAll('.select-all-scopes').forEach(button=>button.addEventListener('click',()=>button.closest('fieldset').querySelectorAll('input[type=checkbox]').forEach(box=>{box.checked=true;})));
    function readTheme(){const colors={},styles={};Object.keys(cfg.themes['classic-gold'].colors).forEach(k=>colors[k]=field('colors['+k+']').value);Object.keys(cfg.styles).forEach(k=>{const f=field('styles['+k+']');styles[k]=['bodySize','radius','borderWidth'].includes(k)?Number(f.value):f.value;});return {name:field('name').value,font:field('font').value,colors,styles};}
    const luminance=hex=>{const rgb=[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722;};
    function warnings(t){const c=t.colors,result=[],contrast=(a,b)=>{const x=luminance(a),y=luminance(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05);};for(const k of ['background','surface'])if(contrast(c.text,c[k])<4.5)result.push('Low contrast between '+(k==='surface'?'panel':'page')+' background and text.');if(contrast(c.accent,c.background)<3)result.push('Headings and navigation accent may be difficult to read.');if(t.styles.bodySize<16)result.push('Body font size is below the recommended minimum.');if(t.styles.background||t.styles.artwork||backgroundBlob)result.push('Check text over the background image at desktop and mobile sizes.');return result;}
    function update(){const t=readTheme();live.contentWindow?.postMessage({type:'dreamgrid-design-preview',theme:t,background:backgroundBlob},location.origin);const box=document.getElementById('editor-warnings');box.replaceChildren();const heading=document.createElement('strong');heading.textContent='Readability checks';box.append(heading);const list=document.createElement('ul');const messages=warnings(t);for(const message of messages.length?messages:['No palette warnings. Review the final page and any images before Apply.']){const li=document.createElement('li');li.textContent=message;list.append(li);}box.append(list);}
    live.addEventListener('load',()=>{if(live.src!=='about:blank')update();});form.addEventListener('input',update);form.addEventListener('change',update);
    field('themeBackground').addEventListener('change',()=>{if(backgroundBlob)URL.revokeObjectURL(backgroundBlob);const file=field('themeBackground').files[0];backgroundBlob=file?URL.createObjectURL(file):'';update();});
    editArea.addEventListener('change',()=>{live.src='/Other/site-theme-preview.php?scope='+encodeURIComponent(editArea.value);});
    document.querySelectorAll('.edit-theme').forEach(button=>button.addEventListener('click',()=>{
        form.reset();const id=button.dataset.theme,t=structuredClone(cfg.themes[id]),mode=button.dataset.mode,editing=mode==='edit'||mode==='rename';editorOriginal=t;field('themeId').value=editing?id:'';field('action').value=editing?'theme_update':'theme_save';field('name').value=editing?t.name:t.name+' copy';field('font').value=t.font;
        Object.entries(t.colors).forEach(([k,v])=>{field('colors['+k+']').value=v;});Object.entries({...cfg.styles,...t.styles}).forEach(([k,v])=>{field('styles['+k+']').value=v;});backgroundBlob='';editArea.value='public';live.src='/Other/site-theme-preview.php?scope=public';editor.showModal();if(mode==='rename')field('name').focus();update();
    }));
    document.getElementById('preview-customize').addEventListener('click',()=>{preview.close();document.querySelector('.edit-theme[data-theme="'+theme+'"][data-mode="new"]')?.click();});document.getElementById('preview-apply').addEventListener('click',()=>{preview.close();document.querySelector('.preview-theme[data-theme="'+theme+'"]')?.closest('article').querySelector('.open-apply')?.click();});document.getElementById('preview-reset').addEventListener('click',()=>{theme=cfg.activeIds[area.value]||'current';showPreview();});document.getElementById('editor-reset').addEventListener('click',()=>{if(!editorOriginal)return;if(backgroundBlob)URL.revokeObjectURL(backgroundBlob);backgroundBlob='';field('themeBackground').value='';field('name').value=editorOriginal.name;field('font').value=editorOriginal.font;Object.entries(editorOriginal.colors).forEach(([k,v])=>field('colors['+k+']').value=v);Object.entries({...cfg.styles,...editorOriginal.styles}).forEach(([k,v])=>field('styles['+k+']').value=v);update();});
    editor.addEventListener('close',()=>{if(backgroundBlob)URL.revokeObjectURL(backgroundBlob);backgroundBlob='';form.reset();live.src='about:blank';});
    const branding=document.getElementById('branding-form'),brandFrame=document.getElementById('branding-frame');let brandingBlobs={};
    if(branding){const sendBrand=()=>{const b={};Object.keys(cfg.branding).forEach(k=>{b[k]=branding.elements.namedItem('branding['+k+']').value;const remove=branding.elements.namedItem('removeBranding['+k+']');if(remove?.checked)b[k]='';});brandFrame.contentWindow?.postMessage({type:'dreamgrid-design-preview',theme:cfg.active.public,branding:b,brandingImages:brandingBlobs},location.origin);};branding.addEventListener('input',sendBrand);branding.addEventListener('change',event=>{if(event.target.type==='file'){const key=event.target.name;if(brandingBlobs[key])URL.revokeObjectURL(brandingBlobs[key]);const file=event.target.files[0];brandingBlobs[key]=file?URL.createObjectURL(file):'';const card=document.querySelector('[data-brand-image='+key+']');if(card&&file){card.replaceChildren();const image=document.createElement('img');image.src=brandingBlobs[key];image.alt=key+' preview';card.append(image);}}sendBrand();});brandFrame.addEventListener('load',sendBrand);}
    document.querySelectorAll('time[datetime]').forEach(time=>{const value=new Date(time.dateTime);if(!isNaN(value))time.textContent=value.toLocaleString();});
})();
