(() => {
    'use strict';const cfg=JSON.parse(document.getElementById('preview-config').textContent),root=document.documentElement;let localLogo=null;
    const hex=value=>typeof value==='string'&&/^#[a-f0-9]{6}$/i.test(value);
    const safeImage=url=>typeof url==='string'&&(url.startsWith('blob:'+location.origin+'/')||Object.values(cfg.artwork||{}).includes(url)||/^\/Other\/site-design-asset\.php\?file=[a-f0-9]{24}\.(png|jpg|gif|webp)$/.test(url));
    const luminance=hex=>{const rgb=[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722;};
    function accent(color){if(!hex(color))return;root.style.setProperty('--site-accent',color);const l=luminance(color);root.style.setProperty('--site-accent-text',(l+.05)/.05>=1.05/(l+.05)?'#000000':'#ffffff');}
    addEventListener('message',event=>{
        if(event.origin!==location.origin||event.source!==parent||event.data?.type!=='dreamgrid-design-preview')return;const {theme,branding,brandingImages}=event.data;
        if(theme?.colors&&['background','surface','text','muted','accent','border'].every(k=>hex(theme.colors[k]))){
            for(const k of ['background','surface','text','muted','accent','border'])if(hex(theme.colors[k]))root.style.setProperty('--site-'+k,theme.colors[k]);accent(theme.colors.accent);
            root.style.colorScheme=luminance(theme.colors.background)>.5?'light':'dark';if(cfg.fonts[theme.font])root.style.setProperty('--site-font',cfg.fonts[theme.font].css);
            const s=theme.styles||{};if(cfg.treatments?.[s.treatment])document.body.dataset.designTreatment=s.treatment;const scope=document.body.dataset.designScope;root.style.setProperty('--site-hero-spacing',scope==='admin'?'28px':'64px');root.style.setProperty('--site-hero-letter-spacing',['classic','haunted','fantasy'].includes(s.treatment)?'.02em':'-.035em');root.style.setProperty('--site-hero-rule',['classic','editorial','harvest'].includes(s.treatment)?'3px solid var(--site-accent)':'0 solid transparent');const dark=['classic','coastal','botanical','festive','haunted','harvest','fantasy','festival','modern'].includes(s.treatment);root.style.setProperty('--site-panel-treatment',s.panel==='outlined'?'var(--site-background)':scope==='admin'||!dark?'var(--site-surface)':'linear-gradient(145deg,color-mix(in srgb,var(--site-surface) 94%,white),color-mix(in srgb,var(--site-surface) 96%,transparent))');root.style.setProperty('--site-card-shadow',['coastal','fantasy','festival'].includes(s.treatment)?'0 18px 60px rgba(0,0,0,.28)':'0 12px 30px rgba(0,0,0,.10)');const name=document.querySelector('[data-theme-name]');if(name&&typeof theme.name==='string')name.textContent=theme.name;const bounded=(v,min,max)=>Number.isFinite(Number(v))&&Number(v)>=min&&Number(v)<=max;
            if(bounded(s.bodySize,10,28))root.style.setProperty('--site-body-size',s.bodySize+'px');if(bounded(s.radius,0,40)){root.style.setProperty('--site-radius',s.radius+'px');root.style.setProperty('--site-button-radius',(s.button==='pill'?999:s.button==='square'?0:s.radius)+'px');}if(bounded(s.borderWidth,0,5))root.style.setProperty('--site-border-width',s.borderWidth+'px');
            root.style.setProperty('--site-panel-fill',s.panel==='outlined'?'var(--site-background)':'var(--site-surface)');root.style.setProperty('--site-nav-fill',s.navigation==='minimal'?'var(--site-background)':'var(--site-surface)');
            const background=safeImage(event.data.background)?event.data.background:(/^[a-f0-9]{24}\.(png|jpg|gif|webp)$/.test(s.background||'')?'/Other/site-design-asset.php?file='+s.background:(cfg.artwork?.[s.artwork]||''));const overlay=scope==='admin'?'rgba(0,0,0,.65),rgba(0,0,0,.65)':dark?'rgba(0,0,0,.12),rgba(0,0,0,.18)':'rgba(255,255,255,.12),rgba(255,255,255,.12)';const builtIn=background&&Object.values(cfg.artwork||{}).includes(background);root.style.setProperty('--site-background-image',background?(builtIn?'linear-gradient('+overlay+'),':'')+'url("'+background+'")':'none');
        }
        if(branding){const base=cfg.baseIdentity;for(const [selector,key,fallback] of [['.site-brand strong','title','siteTitle'],['[data-brand-heading]','heading','welcomeHeading'],['[data-brand-welcome]','welcome','welcomeText'],['[data-brand-footer]','footer','footer']]){const el=document.querySelector(selector);if(el)el.textContent=typeof branding[key]==='string'&&branding[key]?branding[key]:base[fallback];}accent(branding.accent);
            if(['square','rounded','pill'].includes(branding.button))root.style.setProperty('--site-button-radius',({square:0,rounded:12,pill:999})[branding.button]+'px');
            const image=brandingImages?.logo||(/^[a-f0-9]{24}\.(png|jpg|gif|webp)$/.test(branding.logo||'')?'/Other/site-design-asset.php?file='+branding.logo:'');let logo=document.querySelector('.site-brand-logo');if(safeImage(image)){if(!logo){logo=document.createElement('img');logo.className='site-brand-logo';logo.alt='Logo preview';document.querySelector('.site-brand')?.prepend(logo);}logo.src=image;document.querySelector('.site-brand-default')?.setAttribute('hidden','');}else {logo?.remove();let fallback=document.querySelector('.site-brand-default');if(!fallback){fallback=document.createElement('span');fallback.className='site-brand-default';fallback.textContent='◈';document.querySelector('.site-brand')?.prepend(fallback);}fallback.removeAttribute('hidden');}
            const bg=brandingImages?.background||(/^[a-f0-9]{24}\.(png|jpg|gif|webp)$/.test(branding.background||'')?'/Other/site-design-asset.php?file='+branding.background:'');if(safeImage(bg))root.style.setProperty('--site-background-image','url("'+bg+'")');
        }
    });
})();
