<?php
require_once __DIR__.'/core/bootstrap.php';
require_once __DIR__.'/core/page-designer.php';
ag_no_cache(); ag_require_admin();
if(session_status()!==PHP_SESSION_ACTIVE) session_start();
if(empty($_SESSION['ag_page_designer_csrf'])) $_SESSION['ag_page_designer_csrf']=bin2hex(random_bytes(32));
$csrf=$_SESSION['ag_page_designer_csrf'];
function pd_response($data,$status=200) { http_response_code($status); header('Content-Type: application/json; charset=utf-8'); echo json_encode($data,JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE); exit; }
if(($_SERVER['REQUEST_METHOD'] ?? 'GET')==='POST') {
    try {
        if(!isset($_POST['csrf']) || !is_string($_POST['csrf']) || !hash_equals($csrf,$_POST['csrf'])) throw new RuntimeException('Security token expired or request exceeds the server upload limit. Reload and retry.');
        $action=$_POST['action'] ?? ''; $revision=$_POST['revision'] ?? '';
        $result=function($p){return array('ok'=>true,'page'=>$p,'revision'=>ag_pd_editor_revision($p['id']),'publishing'=>ag_pd_publishing_state($p['id']),'pages'=>ag_pd_editor_pages(),'menuPages'=>ag_pd_menu_pages());};
        if($action==='form_inbox')pd_response(array('ok'=>true,'inbox'=>ag_pf_inbox(!empty($_POST['archived']),$_POST['offset'] ?? 0)));
        if($action==='form_message'){ag_pf_message_action($_POST['messageId'] ?? '',$_POST['operation'] ?? '');pd_response(array('ok'=>true));}
        if($action==='site_inventory')pd_response(array('ok'=>true,'inventory'=>ag_ps_inventory()));
        if($action==='site_replace_preview')pd_response(array('ok'=>true,'preview'=>ag_ps_preview(json_decode($_POST['spec'] ?? '',true))));
        if($action==='site_replace_apply'){ $res=ag_ps_apply(json_decode($_POST['spec'] ?? '',true),json_decode($_POST['expected'] ?? '',true));$current=ag_pd_edit_page($_POST['currentId'] ?? '');if($current)pd_response($result($current)+array('result'=>$res));pd_response(array('ok'=>true,'result'=>$res,'pages'=>ag_pd_editor_pages())); }
        if($action==='site_scan')pd_response(array('ok'=>true,'scan'=>ag_ps_scan($_POST['scope'] ?? 'drafts',$_SERVER['HTTP_HOST'] ?? '')));
        if($action==='template_upload') pd_response(array('ok'=>true,'import'=>ag_ti_upload($_FILES['templateZip'] ?? null)));
        if($action==='template_preview') pd_response(array('ok'=>true,'preview'=>ag_ti_preview($_POST['importToken'] ?? '',$_POST['htmlFile'] ?? '')));
        if($action==='template_import') pd_response($result(ag_ti_commit($_POST['importToken'] ?? '',$_POST['htmlFile'] ?? '',($_POST['reviewed'] ?? '')==='1')));
        if($action==='template_discard'){ag_ti_discard($_POST['importToken'] ?? '');pd_response(array('ok'=>true));}
        if($action==='library_list') pd_response(array('ok'=>true,'items'=>ag_pbl_summary($_POST['kind'] ?? '',!empty($_POST['archived']))));
        if($action==='library_get') pd_response(array('ok'=>true,'entry'=>ag_pbl_download($_POST['kind'] ?? '',$_POST['itemId'] ?? '')));
        if($action==='library_preview') pd_response(array('ok'=>true,'html'=>ag_pbl_preview($_POST['kind'] ?? '',$_POST['itemId'] ?? '',json_decode($_POST['theme'] ?? '{}',true))));
        if($action==='library_save') pd_response(array('ok'=>true,'entry'=>ag_pbl_capture($_POST['kind'] ?? '',json_decode($_POST['page'] ?? '',true),$_FILES,$_POST['nodeId'] ?? '',$_POST['name'] ?? '',$revision)));
        if($action==='library_edit') pd_response(array('ok'=>true,'entry'=>ag_pbl_edit($_POST['kind'] ?? '',$_POST['itemId'] ?? '',$_POST['itemRevision'] ?? '',$_POST['operation'] ?? '',$_POST['name'] ?? '')));
        if($action==='media_list') { $archived=ag_pbl_list('media',true);foreach($archived as &$entry)$entry['revision']=ag_pd_revision($entry);unset($entry);pd_response(array('ok'=>true,'items'=>ag_pbl_media_list(),'archived'=>$archived)); }
        if($action==='media_add') pd_response(array('ok'=>true,'entry'=>ag_pbl_media_add($_FILES['image'] ?? null,$_POST['sourceId'] ?? '',$_POST['file'] ?? '',$_POST['name'] ?? '')));
        if(in_array($action,array('site_get','site_save','site_publish'),true)) {
            if($action!=='site_get') ag_pbl_site_save(json_decode($_POST['site'] ?? '',true),$_POST['siteRevision'] ?? '',$action==='site_publish');
            pd_response(array('ok'=>true,'site'=>ag_pbl_site_edit(),'live'=>ag_pbl_site_live(),'siteRevision'=>ag_pbl_site_revision(),'hasDraft'=>is_file(ag_pd_root().'/site-draft.json'),'sections'=>ag_pbl_summary('section'),'pages'=>ag_pd_editor_pages()));
        }
        if($action==='site_preview') pd_response(array('ok'=>true,'html'=>ag_pbl_site_preview(json_decode($_POST['site'] ?? '',true))));
        if($action==='import') pd_response($result(ag_pd_import_upload($_FILES['package'] ?? null)));
        $id=$_POST['id'] ?? '';
        if($action==='history') pd_response(array('ok'=>true,'items'=>ag_pd_history_list($id)));
        if($action==='revision') { if(!ag_pd_edit_page($id)) throw new RuntimeException('Page not found.'); $e=ag_pd_history_entry($id,$_POST['token'] ?? ''); pd_response(array('ok'=>true,'html'=>ag_pd_render($e['page'],true))); }
        if($action==='restore') pd_response($result(ag_pd_restore_revision($id,$_POST['token'] ?? '',$revision)));
        if($action==='offline') pd_response($result(ag_pd_take_offline($id,$revision)));
        if($action==='export') pd_response(array('ok'=>true,'package'=>ag_pd_export_package($id,$revision)));
        if($action==='delete') {
            ag_pd_lock(function() use($revision) { $p=ag_pd_edit_page($_POST['id'] ?? ''); if(!$p || !hash_equals(ag_pd_editor_revision($p['id']),(string)$revision)) throw new RuntimeException('Page changed or no longer exists. Reload before deleting.'); ag_pd_delete_page($p); });
            pd_response(array('ok'=>true,'menuPages'=>ag_pd_menu_pages()));
        }
        if($action==='publish_check') pd_response(array('ok'=>true,'report'=>ag_pc_check(json_decode($_POST['page'] ?? '',true),json_decode($_POST['pending'] ?? '[]',true),$_SERVER['HTTP_HOST'] ?? '')));
        $input=json_decode($_POST['page'] ?? '',true); if(!is_array($input)) throw new RuntimeException('Invalid page data.');
        if($action==='preview') pd_response(array('ok'=>true,'html'=>ag_pd_render($input,true)));
        if(!in_array($action,array('save','publish'),true)) throw new RuntimeException('Unknown action.');
        $p=ag_pd_commit($input,$_FILES,$revision,$action==='publish'?'publish':'draft');
        pd_response($result($p));
    } catch(Throwable $e) { pd_response(array('ok'=>false,'error'=>$e->getMessage()),400); }
}
$error=''; $pages=array(); $raw=null;
try { $pages=ag_pd_editor_pages(); if(!empty($_GET['id'])) { $raw=ag_pd_edit_page($_GET['id']); if(!$raw) throw new RuntimeException('Page not found.'); } } catch(Throwable $e) { $error=$e->getMessage(); }
$p=$raw ? ag_pd_normalize($raw) : ag_pd_default_page();
function pd_ini_bytes($value) { $value=trim($value); $n=(float)$value; $unit=strtolower(substr($value,-1)); return (int)($n*($unit==='g'?1073741824:($unit==='m'?1048576:($unit==='k'?1024:1)))); }
$gridLinks=array();foreach(array('index.php'=>'Home','welcome.php'=>'Welcome','regions.php'=>'Regions','events.php'=>'Events','search.php'=>'Search','register.php'=>'Register','login.php'=>'Sign in') as $file=>$label)if(is_file(__DIR__.'/'.$file))$gridLinks['/Other/'.$file]=$label;
$config=array('editorNamespace'=>ag_pd_editor_namespace(),'gridLinks'=>$gridLinks,'siteLive'=>ag_pbl_site_live(),'gridName'=>function_exists('ag_grid_name')?ag_grid_name():'','page'=>$p,'pages'=>$pages,'revision'=>$raw?ag_pd_editor_revision($raw['id']):'','publishing'=>$raw?ag_pd_publishing_state($raw['id']):array('published'=>false,'liveSlug'=>'','hasDraft'=>false),'packageLimit'=>min(ag_pd_package_limit(),pd_ini_bytes(ini_get('upload_max_filesize')),max(0,pd_ini_bytes(ini_get('post_max_size'))-65536)),'csrf'=>$csrf,'fonts'=>ag_pd_font_catalog(),'defaults'=>ag_pd_typography_defaults(),'icons'=>ag_pd_menu_icons(),'locations'=>ag_pd_menu_locations(),'menuPages'=>ag_pd_menu_pages(),'postLimit'=>pd_ini_bytes(ini_get('post_max_size')),'fileLimit'=>min(8388608,pd_ini_bytes(ini_get('upload_max_filesize'))),'maxUploads'=>(int)ini_get('max_file_uploads'));
$zipUpload=pd_ini_bytes(ini_get('upload_max_filesize'));$zipPost=pd_ini_bytes(ini_get('post_max_size'));$config['templateZipLimit']=min(33554432,$zipUpload>0?$zipUpload:33554432,$zipPost>0?max(0,$zipPost-65536):33554432);
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Webpage builder · <?=ag_pd_h($config['gridName'])?></title><link rel="stylesheet" href="/Other/page-designer/builder.css?v=interactions-seo-1"><link rel="stylesheet" href="/Other/page-designer/builder-tools.css?v=interactions-seo-1"><link rel="stylesheet" href="/Other/page-designer/builder-editing.css?v=interactions-seo-1"><link rel="stylesheet" href="/Other/page-designer/builder-help.css?v=interactions-seo-1"><link rel="stylesheet" href="/Other/page-designer/builder-publish-check.css?v=interactions-seo-1"><link rel="stylesheet" href="/Other/page-designer/builder-template-import.css?v=interactions-seo-1"><link rel="stylesheet" href="/Other/page-designer/builder-site-management.css?v=interactions-seo-1"></head>
<body><header class="builder-topbar"><div class="brand-mark" aria-hidden="true">◈</div><div class="project-name"><span>WEBPAGE BUILDER</span><button id="page-switch" class="page-switch"><strong id="page-name">Untitled page</strong><span>⌄</span></button></div><span class="save-status" id="save-state">Saved</span><div class="top-spacer"></div><div class="history-tools"><button id="undo" title="Undo (Ctrl+Z)" aria-label="Undo">↶</button><button id="redo" title="Redo (Ctrl+Shift+Z)" aria-label="Redo">↷</button></div><button id="preview-toggle" class="quiet">Preview</button><button id="save-page" class="outline">Save draft</button><button id="publish-page" class="primary">Publish</button></header>
<div class="builder-body"><nav class="tool-rail" aria-label="Builder tools"><button data-panel="add" class="rail-button active" title="Add elements" aria-label="Add elements">＋<small>Add</small></button><button data-panel="layers" class="rail-button" title="Layers" aria-label="Layers">▱<small>Layers</small></button><button data-panel="pages" class="rail-button" title="Pages" aria-label="Pages">▤<small>Pages</small></button><button id="templates" class="rail-button" title="Page templates" aria-label="Page templates">▦<small>Layouts</small></button><div class="rail-spacer"></div><button id="page-settings" class="rail-button" title="Page settings" aria-label="Page settings">⚙<small>Page</small></button><button id="revision-history" class="rail-button" title="Saved revision history" aria-label="Saved revision history">◷<small>History</small></button><button id="transfer-pages" class="rail-button" title="Import and export pages" aria-label="Import and export pages">⇅<small>Transfer</small></button><button id="theme-settings" class="rail-button" title="Page theme" aria-label="Page theme">◐<small>Theme</small></button></nav>
<aside class="library-panel"><div class="panel-heading"><h2 id="library-title">Add to your page</h2><span id="library-count"></span></div><div id="library"></div><div class="library-footer">Click to insert · drag to place</div></aside>
<main class="canvas-workspace"><div class="canvas-toolbar"><div class="device-switch" role="group" aria-label="Canvas device"><button data-device="1280" class="active" aria-label="Desktop preview">▰ <span>Desktop</span></button><button data-device="768" aria-label="Tablet preview">▯ <span>Tablet</span></button><button data-device="390" aria-label="Phone preview">▯ <span>Phone</span></button></div><span id="canvas-size">1280 px</span><div class="toolbar-spacer"></div><select id="canvas-zoom" aria-label="Canvas zoom"><option value="fit">Fit</option><option value="0.5">50%</option><option value="0.75">75%</option><option value="1">100%</option></select><button id="open-page" class="icon-button" aria-label="Open saved page" title="Open saved page">↗</button></div><div id="notice" class="notice" role="status" aria-live="polite"><?=ag_pd_h($error)?></div><div class="canvas-scroll" id="canvas-scroll"><div class="canvas-label"><span id="canvas-page-label">PAGE CANVAS</span><span>Double-click text to edit</span></div><div id="canvas-shell"><iframe id="canvas" title="Visual page canvas" sandbox="allow-same-origin"></iframe></div><button id="append-section" class="append-section">＋ Add a section</button></div><footer class="canvas-footer"><span id="selection-path">Page canvas</span><span id="element-count">0 elements</span><span class="shortcut-hint">Ctrl+S save · Ctrl+Z undo</span></footer></main>
<aside class="inspector-panel"><div class="inspector-heading"><div><span class="eyebrow" id="inspector-kicker">PAGE</span><h2 id="inspector-title">Design your page</h2></div><button id="deselect" class="icon-button" aria-label="Clear selection">×</button></div><div class="inspector-tabs"><button data-inspector-tab="content" class="active">Content</button><button data-inspector-tab="style">Style</button><button data-inspector-tab="layout">Layout</button></div><form id="inspector"></form></aside></div>
<dialog id="template-dialog"><div class="dialog-head"><div><span class="eyebrow">START WITH A STRONG FOUNDATION</span><h2>A complete page. Made yours.</h2><p>Choose a layout, then change everything on the canvas.</p></div><button id="close-templates" class="icon-button" aria-label="Close templates">×</button></div><div id="template-list" class="template-list"></div><p class="dialog-note">Applying a layout replaces unsaved canvas content. Undo brings it back.</p></dialog>
<dialog id="history-dialog"><div class="dialog-head"><div><span class="eyebrow">SAVED VERSIONS</span><h2>Revision history</h2><p>Preview an earlier version. Restore it as a private draft when ready.</p></div><button id="close-history" class="icon-button" aria-label="Close revision history">×</button></div><div class="revision-workspace"><div id="revision-list"></div><div class="revision-preview"><p id="revision-caption">Select a version to preview it.</p><iframe id="revision-canvas" title="Revision preview" sandbox="allow-same-origin"></iframe><button id="restore-revision" class="primary" disabled>Restore as draft</button></div></div><p id="history-notice" class="dialog-note" role="status"></p></dialog>
<dialog id="transfer-dialog"><div class="dialog-head"><div><span class="eyebrow">PORTABLE PAGES</span><h2>Take your page with you.</h2><p>Move saved content and images between DreamGrid installations.</p></div><button id="close-transfer" class="icon-button" aria-label="Close page transfer">×</button></div><div class="transfer-grid"><section><h3>Export this page</h3><p>Download one DreamGrid package containing your saved draft (or published page) and its images. External links and video URLs remain links.</p><button id="export-page" class="outline">Download page package</button></section><section><h3>Import a page</h3><p>Import creates a new private draft with a new page ID. Existing pages stay in place.</p><label for="import-package">DreamGrid page package</label><input id="import-package" type="file" accept=".json,application/json"><button id="import-page" class="primary">Import as new draft</button><small id="package-limit"></small></section></div><p id="transfer-notice" class="dialog-note" role="status"></p></dialog>
<script id="designer-config" type="application/json"><?=json_encode($config,JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_UNESCAPED_UNICODE)?></script><script src="/Other/page-designer/builder-presets.js?v=interactions-seo-1" defer></script><script src="/Other/page-designer/builder-convert.js?v=interactions-seo-1" defer></script><script src="/Other/page-designer/builder-editing-model.js?v=interactions-seo-1" defer></script><script src="/Other/page-designer/interactions-public.js?v=interactions-seo-1" defer></script><script src="/Other/page-designer/builder-interactions.js?v=interactions-seo-1" defer></script><script src="/Other/page-designer/builder.js?v=interactions-seo-1" defer></script><script src="/Other/page-designer/builder-tools.js?v=interactions-seo-1" defer></script><script src="/Other/page-designer/builder-editing.js?v=interactions-seo-1" defer></script><script src="/Other/page-designer/builder-help-content.js?v=interactions-seo-1" defer></script><script src="/Other/page-designer/builder-help.js?v=interactions-seo-1" defer></script><script src="/Other/page-designer/builder-publish-check.js?v=interactions-seo-1" defer></script><script src="/Other/page-designer/builder-template-import.js?v=interactions-seo-1" defer></script><script src="/Other/page-designer/builder-forms.js?v=interactions-seo-1" defer></script><script src="/Other/page-designer/builder-site-management.js?v=interactions-seo-1" defer></script></body></html>
