(() => {'use strict';
 const B=window.DreamGridBuilder,M=window.DreamGridEditingModel,E=B.create,namespace=B.config.editorNamespace,owner=crypto.randomUUID();
 let db,queue=Promise.resolve(),timer,loading=true,lastKey=key(),candidate=null,clipboardReady=false;
 const status=E('span',{id:'recovery-status',class:'recovery-status',role:'status'},'Starting recovery…');
 document.querySelector('.canvas-footer').append(status);
 const controls=E('div',{class:'editing-toolbar','aria-label':'Selection tools'});
 const button=(name,fn,cls='small-button')=>{const e=E('button',{type:'button',class:cls},name);e.onclick=()=>safe(fn);return e;};
 const multi=button('Multi-select',()=>{B.setMultiMode(!B.multiMode);selectionChanged();});multi.setAttribute('aria-pressed','false');
 const copyButton=button('Copy',copySelection),pasteButton=button('Paste',paste),lockButton=button('Lock',()=>setLocks(true)),recoveryButton=button('Recovery',openRecovery);
 controls.append(multi,copyButton,pasteButton,lockButton,recoveryButton);document.querySelector('.canvas-toolbar').after(controls);
 const notice=(text,error=false)=>{status.textContent=text;status.classList.toggle('error',error);};
 function key(){return namespace+':recovery:'+(B.page.id||'new');}
 async function safe(fn){try{if(B.busy)return;await fn();}catch(e){B.show(e.message,true);}}
 function storage(mode,operation){return new Promise((resolve,reject)=>{if(!db){reject(Error('Browser storage is unavailable. Use Save draft to retain your work.'));return;}const tx=db.transaction('editor',mode),store=tx.objectStore('editor');let result;const request=operation(store);request.onsuccess=()=>result=request.result;tx.oncomplete=()=>resolve(result);tx.onabort=tx.onerror=()=>reject(tx.error||Error('Browser storage could not save this work.'));});}
 const read=k=>storage('readonly',s=>s.get(k)),write=(k,value)=>storage('readwrite',s=>s.put(value,k));
 function enqueue(fn){queue=queue.then(fn).catch(e=>notice(e.message,true));return queue;}
 function changed(){if(loading)return;clearTimeout(timer);if(!B.dirty){saved(B.page.id);return;}notice('Recovery pending…');timer=setTimeout(()=>{const snapshot=B.snapshot(),record={version:1,owner,namespace,pageId:B.page.id,revision:B.revision,saved:Date.now(),snapshot};const targetKey=key();lastKey=targetKey;enqueue(async()=>{await write(targetKey,record);notice('Recovery saved '+new Date(record.saved).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}));});},650);}
 function saved(oldId){clearTimeout(timer);const oldKey=namespace+':recovery:'+(oldId||'new');enqueue(async()=>{const record=await read(oldKey);if(record?.owner===owner)await storage('readwrite',s=>s.delete(oldKey));notice('Saved draft · recovery current');});}
 function openRecovery(){safe(async()=>{const record=await read(key());if(!record){B.show('There is no unsaved recovery for this page.');return;}showRecovery(record);});}
 function showRecovery(record){if(document.querySelector('#recovery-dialog'))return;const d=E('dialog',{id:'recovery-dialog',class:'recovery-dialog'}),h=E('div',{class:'dialog-head'}),intro=E('div');intro.append(E('span',{class:'eyebrow'},'BROWSER RECOVERY'),E('h2',{},'Your unsaved work is here.'),E('p',{},(record.snapshot.page.title||'Untitled page')+' · '+new Date(record.saved).toLocaleString()));h.append(intro);const body=E('div',{class:'recovery-body'});body.append(E('p',{},'This includes page content, device styles and pending image uploads. Restoring opens unsaved edits for you to review; Save draft and Publish remain separate actions.'));if(record.revision!==B.revision)body.append(E('p',{class:'recovery-warning'},'The saved page has changed since this recovery. Review the recovered content before saving it over the current draft.'));
 const close=()=>{d.close();d.remove();};body.append(button('Restore unsaved work',async()=>{if(B.dirty&&!confirm('Replace current unsaved edits with this recovery? Undo restores the current canvas.'))return;const snapshot=record.snapshot;if(snapshot.page.id!==B.page.id)throw Error('Recovery belongs to another page.');M.validate(snapshot.page.builder.blocks);B.mutate(()=>{},'',false);B.restore({...snapshot,dirty:true});loading=false;record.owner=owner;enqueue(()=>write(key(),record));close();changed();B.show('Recovered unsaved work. Review it, then save a draft.');},'primary'),button('Keep for later',close),button('Discard recovery',async()=>{await storage('readwrite',s=>s.delete(key()));close();notice('Recovery discarded');if(B.dirty)changed();}));d.append(h,body);document.body.append(d);d.showModal();d.addEventListener('cancel',()=>d.remove());}
 function isLocked(id){if(!id)return false;if(id.startsWith('card:')){let legacy=null;M.walk(B.page.builder.blocks,n=>{if(n.type==='legacy')legacy=n.id;});id=legacy;}return !!M.lockOwner(B.page.builder.blocks,id);}
 function isProtected(id){return id?.startsWith('card:')?isLocked(id):M.protectedNode(B.page.builder.blocks,id);}
 function legacyLocked(){if(isLocked('card:legacy')){B.show('Unlock the Existing page section before editing its cards.',true);return true;}return false;}
 function ids(){return B.selection;}
 function selectionChanged(){const selected=ids();multi.classList.toggle('active',B.multiMode);multi.setAttribute('aria-pressed',String(B.multiMode));copyButton.disabled=!selected.length||B.busy;lockButton.disabled=!selected.length||B.busy;pasteButton.disabled=!db||B.busy;lockButton.textContent=selected.length&&selected.every(id=>B.find(id)?.node.locked)?'Unlock':'Lock';lockButton.onclick=()=>safe(()=>setLocks(!selected.every(id=>B.find(id)?.node.locked)));
 const path=document.getElementById('selection-path');path.replaceChildren();path.setAttribute('aria-label','Element breadcrumbs');const crumb=(name,id)=>{const b=button(name,()=>{if(B.multiMode)B.setMultiMode(false);B.select(id,true);},'breadcrumb');if(id)b.setAttribute('data-crumb-id',id);path.append(b);};crumb('Page',null);let f=B.selected&&B.find(B.selected.id),trail=[];while(f){trail.unshift(f.node);f=f.parent?B.find(f.parent.id):null;}for(const n of trail){path.append(E('span',{class:'breadcrumb-separator','aria-hidden':'true'},'›'));crumb(n.name+(n.locked?' · locked':''),n.id);}if(selected.length>1)path.append(E('span',{class:'selection-total'},selected.length+' selected'));
 }
 function decorateInspector(parent,node){if(!node&&B.selectedId?.startsWith('card:'))M.walk(B.page.builder.blocks,n=>{if(n.type==='legacy'&&M.lockOwner(B.page.builder.blocks,n.id))node=n;});if(!node)return;const owner=M.lockOwner(B.page.builder.blocks,node.id);if(owner){for(const child of [...parent.children])child.inert=true;const box=E('div',{class:'lock-banner'});box.append(E('strong',{},owner.id===node.id?'This element is locked.':'Protected by '+owner.name),E('p',{},'Content, styling, movement and deletion are protected. Copying remains available.'));box.append(button(owner.id===B.selectedId?'Unlock element':'Select locked parent',()=>owner.id===B.selectedId?setLocks(false):B.select(owner.id,true)));parent.prepend(box);}else{const row=E('div',{class:'lock-controls'});row.append(button('Lock element',()=>setLocks(true)));parent.prepend(row);} }
 function multiInspector(parent){const selected=ids();if(selected.length<2)return false;document.querySelector('.inspector-tabs').hidden=true;document.getElementById('inspector-kicker').textContent='MULTIPLE ELEMENTS';document.getElementById('inspector-title').textContent=selected.length+' selected';const p=E('div',{class:'multi-inspector'});p.append(E('p',{},'Ctrl/Shift-click elements or use Multi-select. Selecting a parent includes its contents once in grouped operations.'));for(const [name,fn]of [['Copy selected',copySelection],['Duplicate selected',duplicate],['Move up',()=>shift(-1)],['Move down',()=>shift(1)],['Lock selected',()=>setLocks(true)],['Unlock selected',()=>setLocks(false)],['Delete selected',remove]])p.append(button(name,fn));parent.append(p);return true;}
 function setLocks(value){const selected=M.roots(B.page.builder.blocks,ids());if(!selected.length)throw Error('Select elements first.');for(const n of selected){const owner=M.lockOwner(B.page.builder.blocks,n.id);if(owner&&owner.id!==n.id)throw Error('Select and unlock '+owner.name+' first.');}B.mutate(()=>{for(const n of selected)n.locked=value;},'',true);B.refresh();B.show(value?'Selected content locked.':'Selected content unlocked.');}
 function operation(fn,label){const before=M.clone(B.page.builder.blocks),result=fn(before);B.mutate(()=>B.page.builder.blocks=before,'',true);if(Array.isArray(result))B.setSelection(result);else B.setSelection(ids());B.refresh();B.show(label);}
 function remove(){operation(nodes=>{M.remove(nodes,ids());return[];},'Selected elements removed. Undo is available.');}
 function shift(delta){operation(nodes=>M.shift(nodes,ids(),delta),'Selected elements reordered.');}
 function move(source,target,inside){safe(()=>operation(nodes=>M.relocate(nodes,ids().includes(source)?ids():[source],target,inside),'Moved selected content.'));}
 function moveToRoot(source){safe(()=>operation(nodes=>M.moveToRoot(nodes,ids().includes(source)?ids():[source]),'Moved selected content to page root.'));}
 function duplicate(){const nodes=M.clone(B.page.builder.blocks),result=M.duplicate(nodes,ids(),()=>B.presets.node('text').id);if(!result.ids.length)throw Error('Select native elements first.');B.mutate(()=>{B.page.builder.blocks=nodes;for(const [old,id]of result.imagePairs)if(B.files.has('block_image_'+old))B.files.set('block_image_'+id,B.files.get('block_image_'+old));B.resetUrls();},'',true);B.setSelection(result.ids);B.refresh();B.show('Duplicated selected content.');}
 async function copySelection(){const nodes=M.clone(M.roots(B.page.builder.blocks,ids()));if(!nodes.length)throw Error('Select native elements first.');let legacy=false;M.walk(nodes,n=>{if(n.type==='legacy')legacy=true;});if(legacy)throw Error('Convert Existing page content to native elements before copying it between pages.');const assets={};let size=0;const images=[];M.walk(nodes,n=>{if(n.props.image||B.files.has('block_image_'+n.id))images.push(n);});for(const n of images){let file=B.files.get('block_image_'+n.id);if(!file){const response=await fetch('/Other/custom-page-asset.php?page='+encodeURIComponent(B.page.id)+'&file='+encodeURIComponent(n.props.image),{credentials:'same-origin'});if(!response.ok)throw Error('A selected image could not be copied.');const blob=await response.blob();file=new File([blob],n.props.image,{type:blob.type});}if((size+=file.size)>33554432)throw Error('Copied image data exceeds 32 MB. Select fewer elements.');const token='asset-'+n.id;assets[token]=file;n.props.image=token;}
 await enqueue(async()=>{await write(namespace+':clipboard',{version:1,namespace,nodes,assets,saved:Date.now()});clipboardReady=true;selectionChanged();B.show('Copied '+nodes.length+' top-level elements with their images. Open another page and choose Paste.');});}
 async function paste(){const clip=await read(namespace+':clipboard');if(!clip||clip.version!==1||clip.namespace!==namespace)throw Error('Copy elements in this DreamGrid builder first.');const add=M.clone(clip.nodes),pending=[];M.walk(add,n=>{n.id=B.presets.node('text').id;if(n.props.image){const file=clip.assets[n.props.image];if(!(file instanceof Blob))throw Error('Clipboard image is missing.');pending.push(['block_image_'+n.id,file instanceof File?file:new File([file],'copied-image',{type:file.type})]);n.props.image='';}});const nodes=M.clone(B.page.builder.blocks);M.append(nodes,add,B.selected?.id||null);B.mutate(()=>{B.page.builder.blocks=nodes;for(const [k,f]of pending)B.files.set(k,f);B.resetUrls();},'',true);B.setSelection(add.map(n=>n.id));B.refresh();B.show('Pasted editable content with independent images. Save draft when ready.');}
 function keyHandler(e){if(!(e.ctrlKey||e.metaKey))return false;const k=e.key.toLowerCase();if(k==='c'){e.preventDefault();safe(copySelection);return true;}if(k==='v'){e.preventDefault();safe(paste);return true;}if(k==='a'){e.preventDefault();B.setSelection(B.page.builder.blocks.map(n=>n.id));return true;}return false;}
 window.DreamGridEditing={changed,saved,selectionChanged,decorateInspector,multiInspector,isLocked,isProtected,legacyLocked,move,moveToRoot,duplicate:()=>safe(duplicate),remove:()=>safe(remove),shift:delta=>safe(()=>shift(delta)),key:keyHandler};
 window.addEventListener('beforeunload',()=>{if(B.dirty){clearTimeout(timer);const record={version:1,owner,namespace,pageId:B.page.id,revision:B.revision,saved:Date.now(),snapshot:B.snapshot()};if(db)write(key(),record).catch(()=>{});}});
 try{const open=indexedDB.open('DreamGridPageEditor',1);open.onupgradeneeded=()=>open.result.createObjectStore('editor');open.onerror=()=>{loading=false;notice('Recovery unavailable · use Save draft',true);};open.onsuccess=()=>{db=open.result;db.onversionchange=()=>db.close();(async()=>{candidate=await read(key());clipboardReady=!!await read(namespace+':clipboard');loading=false;notice(candidate?'Unsaved recovery available':'Recovery ready');selectionChanged();if(candidate&&candidate.namespace===namespace&&candidate.pageId===B.page.id){document.getElementById('template-dialog').close();showRecovery(candidate);}else if(B.dirty)changed();})().catch(e=>{loading=false;notice(e.message,true);});};}catch(e){loading=false;notice('Recovery unavailable · use Save draft',true);}
 B.renderInspector();selectionChanged();
})();
