/* Editable component and page recipes. Branding is supplied by the local grid. */
window.DreamGridPresets = (brand) => {
    const id=()=>Array.from(crypto.getRandomValues(new Uint8Array(6)),n=>n.toString(16).padStart(2,'0')).join('');
    const node=(type,props={},style={},children=[],name)=>({id:id(),type,name:name||type[0].toUpperCase()+type.slice(1),props,style,children});
    const heading=(text,size=36)=>node('heading',{text,tag:'h2'},{fontSize:size});
    const text=(value)=>node('text',{text:value},{});
    const section=(children,name,style={})=>node('section',{}, {padding:32,paddingY:64,gap:24,...style},children,name);
    const features=()=>section([node('heading',{text:'Make room for something remarkable.',tag:'h2'},{align:'center',fontSize:38}),node('text',{text:'A place to discover, connect and create.'},{align:'center',color:'muted'}),node('columns',{}, {columns:3,tabletColumns:2,mobileColumns:1,gap:24},['Explore','Connect','Create'].map((name,index)=>section([heading(String(index+1).padStart(2,'0'),20),heading(name,24),text('Tell visitors what makes this experience special. Replace this text with your own story.')],name,{background:'surface',radius:16,padding:28,paddingY:32,gap:16,shadow:'soft'})),'Feature grid')],'Features',{background:'background'});
    const cta=()=>section([heading('Your next chapter starts here.',42),text('Invite your visitors to take the next step.'),node('button',{label:'Get started',url:'#welcome'},{align:'center'})],'Call to action',{align:'center',background:'surface',gap:22});
    const defaults={
        section:()=>section([],'Blank section'),
        columns:()=>node('columns',{}, {columns:2,tabletColumns:2,mobileColumns:1,gap:24},[section([heading('First column',24),text('Add content to this column.')],'Column 1',{padding:24,paddingY:24,gap:16}),section([heading('Second column',24),text('Add content to this column.')],'Column 2',{padding:24,paddingY:24,gap:16})],'Two columns'),
        heading:()=>heading('A heading with purpose.'),
        text:()=>text('Every great page tells a story. Click here and make this one yours.'),
        image:()=>node('image',{image:'',alt:''},{radius:16,height:300,fit:'cover'}),
        button:()=>node('button',{label:'Explore more',url:'',newTab:false},{}),
        tabs:()=>node('tabs',{defaultPanel:1},{padding:32},[section([heading('Explore'),text('Build this panel with your own elements.')],'Explore',{padding:24,paddingY:24}),section([heading('Discover'),text('Select this panel in Layers to add images, buttons or forms.')],'Discover',{padding:24,paddingY:24})],'Tabs'),
        accordion:()=>node('accordion',{singleOpen:true,startClosed:false,defaultPanel:1},{padding:32},[section([text('Add native elements to this expandable panel.')],'Getting started',{padding:24,paddingY:24}),section([text('Replace this content with helpful details.')],'More information',{padding:24,paddingY:24})],'Accordion'),
        'site-branding':()=>node('site-branding',{}, {padding:24},[],'Site Branding'),
    'grid-login':()=>node('grid-login',{}, {padding:32,width:'narrow'},[],'Member Login'),
        form:()=>node('form',{title:'Get in touch',text:'Send us a message.',buttonLabel:'Send message',successMessage:'Thank you. Your message has been received.',handling:'local',recipient:'',fields:[{id:id(),type:'text',label:'Your name',required:true,maxLength:120},{id:id(),type:'email',label:'Email address',required:true,maxLength:254},{id:id(),type:'textarea',label:'Message',required:true,maxLength:5000}]},{padding:32,radius:16},[],'Contact form'),
        navigation:()=>node('navigation',{brand,useGridName:true,items:[{label:'Discover',url:'#discover'},{label:'About',url:'#about'}],buttonLabel:'Get in touch',buttonUrl:'#contact'},{},[],'Navigation'),
        hero:()=>node('hero',{anchor:'welcome',kicker:'WELCOME TO',useGridName:true,title:'A world of possibilities.\nBuilt by you.',subtitle:'Discover new places, meet your people and bring your ideas to life.',buttonLabel:'Start exploring',buttonUrl:'#discover',image:'',alt:''},{paddingY:80},[],'Hero'),
        gallery:()=>node('gallery',{}, {columns:3,tabletColumns:2,mobileColumns:1,gap:20},Array.from({length:3},()=>node('image',{image:'',alt:''},{height:280,radius:16,fit:'cover'})),'Image gallery'),
        quote:()=>node('quote',{text:'Great things happen when people have a place to create together.',attribution:'A member of your community'},{},[],'Quote'),
        faq:()=>node('faq',{items:[{question:'How do I get started?',answer:'Explain the first step for your visitors here.'},{question:'Where can I learn more?',answer:'Add helpful information and guide visitors to their next step.'}]},{},[],'Frequently asked questions'),
        stats:()=>node('stats',{items:[{value:'01',label:'Discover something new'},{value:'02',label:'Connect with your people'},{value:'03',label:'Create your own story'}]},{columns:3,mobileColumns:1},[],'Highlights'),
        video:()=>node('video',{videoUrl:'',image:''},{radius:16},[],'Video'),
        divider:()=>node('divider',{},{}), spacer:()=>node('spacer',{}, {height:64}),
        footer:()=>node('footer',{brand,useGridName:true,text:'A place for your next great idea.',items:[{label:'Back to top',url:'#welcome'}]},{}),
        features,cta
    };
    const about=()=>section([node('columns',{}, {columns:2,tabletColumns:2,mobileColumns:1,gap:64},[section([heading('A little about us.',42),text('Share your mission, your people and the idea that brought you together. Give visitors a reason to be part of your story.'),node('button',{label:'Get in touch',url:'#contact'}, {})],'Our story',{padding:0,paddingY:16,gap:24}),defaults.image()],'About columns')],'About',{paddingY:80});
    const contact=()=>section([heading('Let’s make something happen.',38),text('Add your contact details or a link to the best way to reach you.'),node('button',{label:'Contact us',url:''},{})],'Contact',{background:'surface',align:'center'});
    const recipes={
        landing:{label:'Launch & discover',category:'LANDING PAGE',description:'A confident introduction with a hero, features, story and call to action.',blocks:()=>[defaults.navigation(),defaults.hero(),Object.assign(features(),{props:{anchor:'discover'}}),Object.assign(about(),{props:{anchor:'about'}}),Object.assign(contact(),{props:{anchor:'contact'}}),defaults.footer()]},
        community:{label:'Community hub',category:'COMMUNITY',description:'Introduce your community, highlight experiences and answer common questions.',blocks:()=>[defaults.navigation(),defaults.hero(),section([defaults.stats()],'Highlights',{paddingY:32}),Object.assign(features(),{props:{anchor:'discover'}}),Object.assign(section([heading('A community worth being part of.',40),defaults.quote(),heading('Your questions, answered.'),defaults.faq()],'Community'),{props:{anchor:'about'}}),Object.assign(contact(),{props:{anchor:'contact'}}),defaults.footer()]},
        portfolio:{label:'Showcase & story',category:'PORTFOLIO',description:'Lead with your work, give it context and make it easy to connect.',blocks:()=>[defaults.navigation(),node('hero',{anchor:'welcome',kicker:'A COLLECTION OF POSSIBILITIES',title:'Ideas made visible.',subtitle:'A collection of places, projects and moments worth sharing.',buttonLabel:'View the collection',buttonUrl:'#discover',image:''},{paddingY:70},[],'Showcase hero'),Object.assign(section([heading('Selected work',42),defaults.gallery()],'Work'),{props:{anchor:'discover'}}),Object.assign(about(),{props:{anchor:'about'}}),Object.assign(contact(),{props:{anchor:'contact'}}),defaults.footer()]},
        event:{label:'Gather & celebrate',category:'EVENT PAGE',description:'Set the scene, share the details and give visitors a clear invitation.',blocks:()=>[defaults.navigation(),node('hero',{anchor:'welcome',kicker:'YOU ARE INVITED',title:'Something worth\ncoming together for.',subtitle:'Add your event name, date and location. Make your invitation unforgettable.',buttonLabel:'See the details',buttonUrl:'#discover',image:''},{paddingY:80},[],'Event hero'),Object.assign(section([heading('The details',40),node('stats',{items:[{value:'When',label:'Add your date and time'},{value:'Where',label:'Add your location'},{value:'Who',label:'Everyone is welcome'}]},{columns:3,mobileColumns:1})],'Event details'),{props:{anchor:'discover'}}),Object.assign(section([heading('What to expect'),defaults.columns(),defaults.faq()],'Programme'),{props:{anchor:'about'}}),Object.assign(contact(),{props:{anchor:'contact'}}),defaults.footer()]},
        blank:{label:'Start from a blank canvas',category:'YOUR OWN DESIGN',description:'Your layout, your structure, your ideas. Build it one element at a time.',blocks:()=>[]}
    };
    recipes.landing.label='Landing page';
    const namedAnchor=(node,anchor)=>{node.props.anchor=anchor;return node;};
    const pageNav=items=>{const n=defaults.navigation();n.props.items=items;n.props.buttonLabel='';n.props.buttonUrl='';return n;};
    const pageFooter=anchor=>{const n=defaults.footer();n.props.items=[{label:'Back to top',url:'#'+anchor}];return n;};
    recipes.home={label:'Home',category:'SITE FOUNDATION',description:'A welcoming home page with an introduction, highlights and a clear next step.',blocks:()=>[pageNav([{label:'Discover',url:'#discover'},{label:'Get started',url:'#contact'}]),defaults.hero(),namedAnchor(features(),'discover'),namedAnchor(cta(),'contact'),defaults.footer()]};
    recipes.about={label:'About',category:'YOUR STORY',description:'Share your story, values and people.',blocks:()=>[pageNav([{label:'Our story',url:'#about'},{label:'Our values',url:'#values'}]),namedAnchor(about(),'about'),namedAnchor(features(),'values'),defaults.quote(),namedAnchor(contact(),'contact'),pageFooter('about')]};
    recipes.contact={label:'Contact',category:'GET IN TOUCH',description:'A contact page for your address, opening hours and contact links.',blocks:()=>[pageNav([{label:'Contact',url:'#contact'},{label:'Find us',url:'#location'}]),namedAnchor(contact(),'contact'),namedAnchor(section([heading('Find us'),text('Add your address, opening hours and directions here.')],'Contact details'),'location'),pageFooter('contact')]};
    recipes.shop={label:'Shop-style layout',category:'PRODUCT SHOWCASE',description:'Showcase products with images, descriptions and links. Connect buttons to your shop.',blocks:()=>[pageNav([{label:'Products',url:'#products'}]),namedAnchor(section([heading('Discover your next favourite.',48),text('A curated collection, chosen for you.')],'Shop introduction'),'welcome'),node('columns',{anchor:'products'}, {columns:3,tabletColumns:2,mobileColumns:1,gap:24},['One','Two','Three'].map(label=>section([defaults.image(),heading('Product '+label,24),text('Describe this product and add its price.'),node('button',{label:'View product',url:''},{})],'Product '+label,{background:'surface',radius:16}))),defaults.footer()]};
    return {node,defaults,recipes};
};
