(() => {'use strict';const B=window.DreamGridBuilder,E=B.create,types={text:'Text',email:'Email',tel:'Telephone',url:'Website URL',number:'Number',textarea:'Message',select:'Dropdown',checkbox:'Checkbox'};
const button=(label,fn,cls='outline')=>{const b=E('button',{type:'button',class:cls},label);b.onclick=()=>Promise.resolve().then(fn).catch(e=>B.show(e.message,true));return b;};
const field=(type,label,required=false)=>({id:B.presets.node('text').id,type,label,required,maxLength:type==='textarea'?5000:1000,placeholder:'',help:'',options:type==='select'?['General enquiry','Support','Other']:[]});
function inspector(parent,node){if(node.type!=='form')return;const p=node.props,g=B.group(parent,'Form content');for(const[k,l,t]of [['title','Form title','text'],['text','Introduction','textarea'],['buttonLabel','Submit button','text'],['successMessage','Success message','textarea']])B.field(g,p,k,l,t,{full:true});B.field(g,p,'handling','Submission handling','select',{full:true,choices:{local:'Save locally',email:'Email with delivery backup',both:'Save locally and email'}});B.field(g,p,'recipient','Notification email address','email',{full:true,maxlength:254});g.append(E('p',{class:'inspector-note full'},'Email uses existing DreamGrid SMTP settings. Messages stay in the private inbox for recovery if delivery fails. Registration requests collect interest; they do not create accounts.'));
const presets=E('div',{class:'action-row full'});for(const[label,fields]of [['Contact',[field('text','Your name',true),field('email','Email address',true),field('textarea','Message',true)]],['Feedback',[field('select','Topic',true),field('textarea','Feedback',true),field('email','Email address')]],['Registration request',[field('text','Preferred name',true),field('email','Email address',true),field('textarea','Tell us about yourself'),field('checkbox','I agree to be contacted',true)]]])presets.append(button(label,()=>{if(!B.canInsert(node.id))return;B.mutate(()=>{p.fields=B.copy(fields);p.title=label;p.text='';},'',true);}));g.append(presets);
const wrap=E('div',{class:'form-field-list full'});g.append(wrap);(p.fields||[]).forEach((f,index)=>{const d=E('details',{class:'form-field-editor'});d.open=true;d.append(E('summary',{},(index+1)+'. '+f.label));const inside=E('div',{class:'fields'});d.append(inside);B.field(inside,f,'label','Label','text',{full:true,maxlength:120});const t=B.field(inside,f,'type','Field type','select',{full:true,choices:types});t.addEventListener('change',()=>B.renderInspector());B.field(inside,f,'required','Required','checkbox');if(!['checkbox','select','number'].includes(f.type)){B.field(inside,f,'placeholder','Placeholder','text',{full:true,maxlength:200});B.field(inside,f,'maxLength','Maximum length','number',{min:1,max:f.type==='textarea'?5000:1000,full:true});}B.field(inside,f,'help','Help text','text',{full:true,maxlength:300});
if(f.type==='number'){for(const k of ['min','max']){const input=E('input',{type:'number','aria-label':k==='min'?'Minimum number':'Maximum number',step:'any'});input.value=f[k]??'';const label=E('label',{class:'tool-field'},k==='min'?'Minimum':'Maximum');label.append(input);input.oninput=()=>B.mutate(()=>{if(input.value==='')delete f[k];else f[k]=Number(input.value);},'form-number-'+f.id+k);inside.append(label);}}
if(f.type==='select'){const label=E('label',{class:'tool-field full'},'Options (one per line)'),input=E('textarea',{rows:5,maxlength:3000});input.value=(f.options||[]).join('\n');input.oninput=()=>B.mutate(()=>{f.options=input.value.split('\n').map(s=>s.trim()).filter(Boolean).slice(0,24);},'form-options-'+f.id);label.append(input);inside.append(label);}
const row=E('div',{class:'action-row full'});for(const [label,delta]of [['↑',-1],['↓',1]])row.append(button(label,()=>{if(!B.canInsert(node.id)||index+delta<0||index+delta>=p.fields.length)return;B.mutate(()=>{[p.fields[index],p.fields[index+delta]]=[p.fields[index+delta],p.fields[index]];},'',true);}));row.append(button('Remove field',()=>{if(!B.canInsert(node.id))return;B.mutate(()=>p.fields.splice(index,1),'',true);},'danger'));inside.append(row);wrap.append(d);});
const row=E('div',{class:'action-row full'}),addType=E('select',{'aria-label':'New field type'});for(const[k,v]of Object.entries(types))addType.append(E('option',{value:k},v));row.append(addType,button('Add field',()=>{if(!B.canInsert(node.id))return;if((p.fields||[]).length>=24)throw Error('A form supports up to 24 fields.');B.mutate(()=>{p.fields??=[];p.fields.push(field(addType.value,types[addType.value]));},'',true);}));g.append(row,button('Open submissions',()=>window.DreamGridSiteManagement.inbox()));}
window.DreamGridForms={inspector};
})();
