(() => {'use strict';
 const B=window.DreamGridBuilder,T=window.DreamGridTutorials,E=B.create,storageKey=B.config.editorNamespace+':tutorial-progress-v1';
 let state=T.normalize(null),remember=true,search='',highlightTimer;
 try{state=T.normalize(JSON.parse(localStorage.getItem(storageKey)||'null'));}catch(e){remember=false;}
 const panel=E('aside',{id:'builder-tutorial-panel',class:'tutorial-panel','aria-label':'Builder tutorials',hidden:''});
 const header=E('div',{class:'tutorial-header'}),heading=E('h2',{tabindex:'-1'},'Learn the builder'),status=E('p',{class:'tutorial-storage',role:'status'});
 const button=(text,fn,cls='small-button')=>{const b=E('button',{type:'button',class:cls},text);b.addEventListener('click',fn);return b;};
 const close=button('×',()=>hide(true),'icon-button');close.setAttribute('aria-label','Close tutorials');header.append(heading,close);
 const intro=E('p',{class:'tutorial-intro'},'Learn on a practice draft. You stay in control of saving and publishing.'),searchBox=E('input',{type:'search',placeholder:'Find a lesson…','aria-label':'Search tutorials'}),list=E('nav',{class:'tutorial-lessons','aria-label':'Tutorial lessons'}),article=E('section',{class:'tutorial-step','aria-label':'Current tutorial step'}),footer=E('div',{class:'tutorial-footer'});
 panel.append(header,intro,searchBox,status,list,article,footer);document.body.append(panel);
 const help=button('',()=>open(),'rail-button');help.id='builder-tutorials';help.title='Help & tutorials';help.setAttribute('aria-label','Help & tutorials');help.setAttribute('aria-expanded','false');help.setAttribute('aria-controls',panel.id);help.append(E('span',{},'?'),E('small',{},'Help'));const rail=document.querySelector('.tool-rail');rail.insertBefore(help,rail.querySelector('.rail-spacer'));
 const resume=button('Continue tutorial',()=>open(),'tutorial-resume');resume.hidden=true;document.body.append(resume);
 const contextual=button('?',()=>open(T.context(B.selected?.type)),'icon-button');contextual.title='Tutorial for the selected element';contextual.setAttribute('aria-label','Tutorial for the selected element');document.querySelector('.inspector-heading').append(contextual);
 function persist(){try{localStorage.setItem(storageKey,JSON.stringify(state));remember=true;}catch(e){remember=false;}status.textContent=remember?'Progress is remembered in this browser.':'Tutorials work, but this browser cannot remember your progress.';}
 function open(id){if(B.busy)return;if(document.querySelector('dialog[open]')){B.show('Close the current dialog to open tutorials.');return;}if(id){state=T.normalize({...state,lesson:id,step:0});persist();}panel.hidden=false;resume.hidden=true;help.setAttribute('aria-expanded','true');render();heading.focus();}
 function hide(keep){panel.hidden=true;help.setAttribute('aria-expanded','false');resume.hidden=!keep;help.focus();}
 function renderList(){list.replaceChildren();for(const lesson of T.lessons.filter(l=>(l.title+' '+l.summary+' '+l.steps.map(s=>s.title+' '+s.body).join(' ')).toLowerCase().includes(search))){const selected=lesson.id===state.lesson,done=state.completed.includes(lesson.id);const b=button('',()=>{state=T.normalize({...state,lesson:lesson.id,step:0});persist();render(true);});b.className='tutorial-lesson'+(selected?' active':'');if(selected)b.setAttribute('aria-current','step');b.append(E('strong',{},(done?'✓ ':'')+lesson.title),E('span',{},lesson.summary));list.append(b);}if(!list.children.length)list.append(E('p',{},'No matching lessons. Try images, phone, menus or recovery.'));}
 function showControl(targetId){if(B.busy)return;const target=T.targets[targetId],control=target&&document.querySelector(target.selector);if(!control||control.hidden||control.closest('[hidden]')||control.disabled||control.getClientRects().length===0){B.show(targetId==='layout'?'Select an element first, then open its Layout tab.':'That control is unavailable in the current view. Select an element or save a draft if this lesson needs one.',true);return;}hide(true);document.querySelectorAll('.tutorial-spotlight').forEach(n=>n.classList.remove('tutorial-spotlight'));control.classList.add('tutorial-spotlight');control.scrollIntoView({block:'nearest',inline:'nearest'});control.focus?.();clearTimeout(highlightTimer);highlightTimer=setTimeout(()=>control.classList.remove('tutorial-spotlight'),4500);if(target.activate)control.click();}
 function render(focusStep=false){renderList();article.replaceChildren();footer.replaceChildren();const lesson=T.lessons.find(l=>l.id===state.lesson),step=lesson.steps[state.step];article.append(E('span',{class:'eyebrow'},'STEP '+(state.step+1)+' OF '+lesson.steps.length),E('h3',{tabindex:'-1'},step.title),E('p',{},step.body));const check=E('div',{class:'tutorial-check'});check.append(E('strong',{},'Check your result'),E('p',{},step.check));article.append(check);if(step.target)article.append(button(T.targets[step.target].label,()=>showControl(step.target),'outline'));const back=button('Back',()=>{state=T.advance(state,-1);persist();render(true);});back.disabled=state.step===0;const last=state.step===lesson.steps.length-1,next=button(last?'Mark lesson complete':'Next step',()=>{state=last?T.complete(state):T.advance(state,1);persist();render(true);if(last)B.show('Lesson marked complete. Choose another lesson or continue editing.');},'primary');footer.append(back,next);footer.append(E('p',{class:'tutorial-total'},state.completed.length+' of '+T.lessons.length+' lessons marked complete.'));footer.append(button('Restart this lesson',()=>{state=T.normalize({...state,step:0,completed:state.completed.filter(id=>id!==state.lesson)});persist();render(true);}),button('Continue editing',()=>hide(true)));status.textContent=remember?'Progress is remembered in this browser.':'Tutorials work, but this browser cannot remember your progress.';resume.textContent='Continue tutorial · '+lesson.title;if(focusStep)article.querySelector('h3').focus();}
 window.DreamGridHelp={open};
 searchBox.addEventListener('input',()=>{search=searchBox.value.trim().toLowerCase();renderList();});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.hidden&&panel.contains(e.target)){e.preventDefault();e.stopPropagation();hide(true);}},true);
})();
