(() => {
 'use strict';
 const B=window.DreamGridBuilder,{create:E,copy,request,mutate,show}=B;
 const button=(text,fn,cls='outline')=>{const e=E('button',{type:'button',class:cls},text);e.onclick=()=>run(fn);return e;};
 async function run(fn){try{await fn();}catch(e){show(e.message,true);const n=document.querySelector('dialog[open] .tools-notice');if(n)n.textContent=e.message;}}
 function dialog(title,sub){const d=E('dialog',{class:'tools-dialog'}),head=E('div',{class:'dialog-head'}),intro=E('div');intro.append(E('span',{class:'eyebrow'},'SITE DESIGN TOOLS'),E('h2',{},title),E('p',{},sub));head.append(intro,button('×',()=>d.close(),'icon-button'));const body=E('div',{class:'tools-body'}),notice=E('p',{class:'tools-notice dialog-note',role:'status'});d.append(head,body,notice);document.body.append(d);d.addEventListener('close',()=>d.remove());d.showModal();return{d,body,notice};}
 function input(parent,label,value,change,type='text',choices=null){const w=E('label',{class:'tool-field'}),control=E(choices?'select':'input',choices?{}:{type});w.append(E('span',{},label));if(choices)for(const [v,t]of Object.entries(choices))control.append(E('option',{value:v},t));if(type==='checkbox')control.checked=!!value;else control.value=value??'';control.addEventListener(choices||type==='checkbox'?'change':'input',()=>{change(type==='checkbox'?control.checked:type==='number'?Number(control.value):control.value);});w.append(control);parent.append(w);return control;}
 function row(title,sub){const e=E('section',{class:'tools-item'});e.append(E('strong',{},title),E('small',{},sub));return e;}
 function count(nodes){let n=0;B.traverse(nodes,()=>n++);return n;}
 async function prepare(entry,kind){const pending=[],mapping=new Map();for(const [name,asset]of Object.entries(entry.assets)){const response=await fetch(asset.url,{credentials:'same-origin'});if(!response.ok)throw Error('A library image could not be loaded.');const blob=await response.blob();mapping.set(name,new File([blob],name,{type:blob.type}));}
 const blocks=copy(kind==='section'?[entry.block]:entry.builder.blocks);B.traverse(blocks,n=>{n.id=B.presets.node('text').id;if(n.props.image){pending.push(['block_image_'+n.id,mapping.get(n.props.image)]);n.props.image='';}});
 const theme=kind==='template'?copy(entry.builder.theme):null;if(theme?.backgroundImage){pending.push(['builder_background_image',mapping.get(theme.backgroundImage)]);theme.backgroundImage='';}
 if(pending.some(([,f])=>!f))throw Error('This library item has a missing image.');return{blocks,theme,pending};}
 async function insertSaved(kind,id){if(B.busy)return;if(kind==='template'&&!B.canReplace()||kind==='section'&&!B.canInsert(B.selected?.id))return;const {entry}=await request('library_get',{kind,itemId:id}),prepared=await prepare(entry,kind);if((kind==='section'?B.total():0)+count(prepared.blocks)>240)throw Error('This item would exceed the 240-element limit.');
 let depth=0,location=B.selected&&B.find(B.selected.id);if(kind==='section'&&location){let ancestor=location;while(ancestor.parent){depth++;ancestor=B.find(ancestor.parent.id);}if(['section','columns','gallery','tabs','accordion'].includes(location.node.type))depth++;}const maxDepth=(nodes,d)=>nodes.reduce((max,n)=>Math.max(max,d,maxDepth(n.children,d+1)),d);if(maxDepth(prepared.blocks,depth)>7)throw Error('This insertion would exceed seven nesting levels. Select a higher section first.');
 if(kind==='template'&&B.page.builder.blocks.length&&!confirm('Replace this canvas with the saved template? Undo restores your current work.'))return;
 mutate(()=>{if(kind==='template'){B.page.builder.blocks=prepared.blocks;B.page.builder.theme=prepared.theme;B.page.builder.site=copy(entry.builder.site||{});if(entry.builder.interactions)B.page.builder.interactions=copy(entry.builder.interactions);else delete B.page.builder.interactions;if(entry.builder.tokens)B.page.builder.tokens=copy(entry.builder.tokens);else delete B.page.builder.tokens;}else{const found=B.selected&&B.find(B.selected.id);if(found&&['section','columns','gallery','tabs','accordion'].includes(found.node.type))found.node.children.push(...prepared.blocks);else if(found)found.list.splice(found.list.indexOf(found.node)+1,0,...prepared.blocks);else B.page.builder.blocks.push(...prepared.blocks);}for(const [key,file]of prepared.pending)B.files.set(key,file);B.resetUrls();},'',true);B.refresh();B.select(prepared.blocks[0]?.id||null);if(kind==='template')document.getElementById('template-dialog').close();show('Inserted an editable copy. Save draft when ready.');}
 function capture(kind,node){if(B.busy)return;const ui=dialog(kind==='section'?'Save reusable section':'Save page template','Content and images are stored independently. Future inserts are editable copies.');let name=node?.name||B.page.title||'My template';const field=input(ui.body,'Library name',name,v=>name=v);ui.body.append(button('Save to library',async()=>{name=field.value.trim();if(!name)throw Error('Give this item a name.');await request('library_save',{kind,nodeId:node?.id||'',name},true);ui.d.close();show('Saved to your '+(kind==='section'?'sections':'templates')+' library.');}));}
 async function library(kind){const ui=dialog(kind==='section'?'Reusable sections':'Saved page templates','Preview an item and insert a copy into this page. Archiving keeps existing page copies intact.');let archived=false,search='';const tools=E('div',{class:'tools-controls'}),list=E('div',{class:'tools-list'}),preview=E('iframe',{class:'tools-preview',title:'Library preview',sandbox:'allow-same-origin'});input(tools,'Search','',v=>{search=v.toLowerCase();draw();});input(tools,'Show archived',false,v=>{archived=v;load();},'checkbox');tools.append(button(kind==='section'?'Save selected element':'Save current page',()=>capture(kind,B.selected)));ui.body.append(tools,list,preview);let items=[];
 async function load(){items=(await request('library_list',{kind,archived:archived?'1':''})).items;draw();}
 function draw(){list.replaceChildren();for(const item of items.filter(e=>e.name.toLowerCase().includes(search))){const r=row(item.name,item.elements+' elements · '+item.images+' images');r.append(button('Preview',async()=>preview.srcdoc=(await request('library_preview',{kind,itemId:item.id,theme:JSON.stringify(B.page.builder.theme)})).html));if(!archived)r.append(button(kind==='template'?'Apply template':'Insert copy',async()=>{await insertSaved(kind,item.id);ui.d.close();}));r.append(button('Rename',async()=>{const name=prompt('Library item name',item.name);if(name===null)return;await request('library_edit',{kind,itemId:item.id,itemRevision:item.revision,operation:'rename',name});await load();}),button(archived?'Restore':'Archive',async()=>{await request('library_edit',{kind,itemId:item.id,itemRevision:item.revision,operation:archived?'restore':'archive'});await load();}));list.append(r);}if(!list.children.length)list.append(E('p',{class:'inspector-note'},archived?'No archived items.':'No saved items yet. Select content on the canvas and save it to your library.'));}await load();}
 async function images(target=null,key='image',fileKey=''){if(B.busy)return;const ui=dialog('Image library','Reuse images from pages, saved sections and templates. Uploads here are kept independently of individual pages.');const tools=E('div',{class:'tools-controls'}),grid=E('div',{class:'image-library-grid'});let items=[],term='';input(tools,'Search images','',v=>{term=v.toLowerCase();draw();});const upload=E('input',{type:'file',accept:'image/jpeg,image/png,image/gif,image/webp','aria-label':'Upload library image'});upload.onchange=()=>run(async()=>{const file=upload.files[0];if(!file)return;if(file.size>B.config.fileLimit)throw Error('Image exceeds the server upload limit.');await request('media_add',{image:file,name:file.name});await load();upload.value='';});tools.append(upload);ui.body.append(tools,grid);
 async function choose(item){if(target){const matched=B.selected;if(matched&&!B.canInsert(matched.id))return;}if(!target&&B.total()+2>240)throw Error('This image would exceed the 240-element limit.');const source=item.sources[0];let file=null;if(!(source.kind==='page'&&source.id===B.page.id)){const r=await fetch(source.url,{credentials:'same-origin'});if(!r.ok)throw Error('Image could not be loaded.');const blob=await r.blob();file=new File([blob],source.file,{type:blob.type});}mutate(()=>{if(!target){const n=B.presets.defaults.image();n.props.alt=item.name;B.page.builder.blocks.push(B.presets.node('section',{}, {},[n],'Image section'));target=n.props;key='image';fileKey='block_image_'+n.id;}target[key]=file?'':source.file;B.files.delete(fileKey);if(file)B.files.set(fileKey,file);B.resetUrls();},'',true);B.refresh();ui.d.close();show('Image added to this draft.');}
 function draw(){grid.replaceChildren();for(const item of items.filter(i=>i.name.toLowerCase().includes(term))){const r=E('section',{class:'image-library-card'});r.append(E('img',{src:item.url,alt:item.name,loading:'lazy'}),E('strong',{},item.name),E('small',{},item.width+' × '+item.height+' · '+Math.ceil(item.size/1024)+' KB'));const usage=E('details');usage.append(E('summary',{},'Used in '+item.uses.length+' saved places'));for(const u of item.uses)usage.append(u.pageId?E('a',{href:'/Other/admin-page-designer.php?id='+u.pageId,target:'_blank',rel:'noopener'},u.label):E('p',{},u.label));r.append(usage,button('Use image',()=>choose(item)));
 if(item.library){r.append(button('Rename',async()=>{const name=prompt('Image name',item.name);if(name===null)return;await request('library_edit',{kind:'media',itemId:item.library.id,itemRevision:item.library.revision,operation:'rename',name});await load();}),button('Archive library copy',async()=>{await request('library_edit',{kind:'media',itemId:item.library.id,itemRevision:item.library.revision,operation:'archive'});await load();}));}else{const source=item.sources.find(s=>s.kind==='page');if(source)r.append(button('Keep in library',async()=>{await request('media_add',{sourceId:source.id,file:source.file,name:item.name});await load();}));}grid.append(r);}if(!grid.children.length)grid.append(E('p',{},'No images yet. Upload an image or save a page containing one.'));}
 async function load(){const data=await request('media_list');items=data.items;draw();for(const item of data.archived){const r=row(item.name,'Archived library image');r.append(button('Restore image',async()=>{await request('library_edit',{kind:'media',itemId:item.id,itemRevision:itemRevision(item),operation:'restore'});await load();}));grid.append(r);}}await load();}
 function itemRevision(item){return item.revision;}
 function anchors(){const choices={'#welcome':'Welcome / top'};B.traverse(B.page.builder.blocks,n=>{if(n.props.anchor)choices['#'+n.props.anchor]=n.name+' · #'+n.props.anchor;});return choices;}
 function menu(parent,items,change,depth=0){const box=E('div',{class:'menu-editor',style:'--depth:'+depth});parent.append(box);items.forEach((item,index)=>{const r=E('div',{class:'menu-item'});input(r,'Label',item.label,v=>change(()=>item.label=v));const inferred=item.pageId?'page':item.url?.startsWith('#')?'anchor':item.url?.startsWith('/Other/')?'grid':'url';let type=inferred;const choices={page:'Custom page',grid:'DreamGrid page',url:'URL or local path',anchor:'Section anchor'};
 input(r,'Link type',type,v=>{type=v;change(()=>{delete item.pageId;item.url=v==='anchor'?'#welcome':v==='grid'?'/Other/index.php':'';});renderTarget();},'select',choices);const destination=E('div');r.append(destination);
 function renderTarget(){destination.replaceChildren();if(type==='page'){const opts={'':'Choose a page'};for(const p of (B.config.linkPages||B.pages))opts[p.id]=p.title+' · /'+p.slug;input(destination,'Page',item.pageId||'',v=>change(()=>{item.pageId=v;const page=B.pages.find(p=>p.id===v);item.url=page?'/Other/custom-page.php?page='+encodeURIComponent(page.slug):'';}),'select',opts);}else if(type==='grid')input(destination,'DreamGrid path',item.url,v=>change(()=>item.url=v),'select',B.config.gridLinks||{'/Other/index.php':'Home'});else if(type==='anchor'){input(destination,'Anchor',item.url,v=>change(()=>item.url=v));const opts=anchors();input(destination,'Page sections',opts[item.url]?item.url:'#welcome',v=>change(()=>{item.url=v;renderTarget();}),'select',opts);}else input(destination,'URL',item.url,v=>change(()=>{item.url=v;delete item.pageId;}));}renderTarget();
 const controls=E('div',{class:'menu-actions'});controls.append(button('↑',()=>change(()=>{if(index>0)[items[index-1],items[index]]=[items[index],items[index-1]];},true),'small-button'),button('↓',()=>change(()=>{if(index<items.length-1)[items[index+1],items[index]]=[items[index],items[index+1]];},true),'small-button'),button('Remove',()=>change(()=>items.splice(index,1),true),'small-button'));if(depth<2)controls.append(button('+ Submenu',()=>change(()=>{item.children??=[];if(item.children.length<24)item.children.push({label:'New link',url:''});},true),'small-button'));r.append(controls);if(item.children?.length)menu(r,item.children,change,depth+1);box.append(r);});if(items.length<24)box.append(button('+ Add menu link',()=>change(()=>items.push({label:'New link',url:''}),true),'small-button'));}
 let siteSession=null;
 async function site(tab='styles'){if(B.busy)return;const ui=dialog('Site settings','Save a private site draft, then publish to update pages that use these shared settings.');const data=await request('site_get');B.config.linkPages=data.pages;let draft=copy(data.site),siteRevision=data.siteRevision,active=tab,changed=false,timer,previewSequence=0;siteSession={ui};const tabs=E('div',{class:'tools-tabs'}),form=E('div',{class:'site-form'}),preview=E('iframe',{class:'tools-preview',title:'Site settings preview',sandbox:'allow-same-origin'}),footer=E('div',{class:'tools-controls'});ui.body.append(tabs,form,preview,footer);const status=E('span',{role:'status'},data.hasDraft?'Site draft saved · live site unchanged':'Published site settings');
 function change(fn,rerender=false){fn();changed=true;status.textContent='Unsaved site changes';if(rerender)render();schedule();}
 function schedule(){clearTimeout(timer);timer=setTimeout(()=>run(async()=>{const seq=++previewSequence;const res=await request('site_preview',{site:JSON.stringify(draft)});if(seq===previewSequence&&ui.d.open)preview.srcdoc=res.html;}),200);}
 function render(){tabs.replaceChildren();for(const [key,label]of Object.entries({styles:'Global styles',sections:'Header & footer',navigation:'Navigation'}))tabs.append(button(label,()=>{active=key;render();},active===key?'primary':'quiet'));form.replaceChildren();
 if(active==='styles'){const theme=draft.theme,styles=draft.styles;for(const [key,label]of Object.entries({background:'Page background',surface:'Surface',text:'Text colour',muted:'Secondary text',accent:'Accent colour'}))input(form,label,theme[key],v=>change(()=>theme[key]=v),'color');input(form,'Site font',theme.font,v=>change(()=>theme.font=v),'select',Object.fromEntries(Object.entries(B.config.fonts).map(([k,v])=>[k,v.label])));for(const [key,label]of Object.entries({width:'Site width',radius:'Corner radius'}))input(form,label,theme[key],v=>change(()=>theme[key]=v),'number');for(const [key,label]of Object.entries({headingSize:'Heading size',textSize:'Body text size',sectionSpacing:'Section spacing',gap:'Element gap',buttonRadius:'Button radius',buttonX:'Button horizontal padding',buttonY:'Button vertical padding'}))input(form,label,styles[key],v=>change(()=>styles[key]=v),'number');form.append(E('p',{class:'inspector-note'},'Explicit element settings take priority. Enable “Use global site styles” in each page’s settings.'));}
 else if(active==='sections'){const choices={'':'None'};for(const e of data.sections)choices[e.id]=e.name;for(const key of ['header','footer'])input(form,'Shared '+key,draft[key],v=>change(()=>draft[key]=v),'select',choices);form.append(E('p',{class:'inspector-note'},'Build a header or footer on a page, save it as a reusable section, then select it here. Enable it on the pages that should display it. To update one, save a revised section and assign it here.'));}
 else menu(form,draft.navigation,change);
 }
 async function save(publish){const res=await request(publish?'site_publish':'site_save',{site:JSON.stringify(draft),siteRevision});draft=copy(res.site);siteRevision=res.siteRevision;changed=false;render();B.config.siteLive=res.live;status.textContent=publish?'Site settings published':'Site draft saved · live site unchanged';ui.notice.textContent=publish?'Updated pages that use these shared settings.':'Site draft saved. Publish when ready.';B.schedulePreview();schedule();}
 footer.append(status,button('Save site draft',()=>save(false)),button('Publish site changes',()=>save(true),'primary'));ui.d.querySelector('.dialog-head button').onclick=()=>{if(!changed||confirm('Close without saving these site changes?'))ui.d.close();};const unload=e=>{if(changed){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',unload);ui.d.addEventListener('cancel',e=>{if(changed&&!confirm('Close without saving these site changes?'))e.preventDefault();});ui.d.addEventListener('close',()=>{clearTimeout(timer);window.removeEventListener('beforeunload',unload);siteSession=null;});render();schedule();}
 function inspector(parent,node,mode){if(mode==='page'){const g=B.group(parent,'Shared site settings');B.page.builder.site??={};for(const [key,label]of Object.entries({styles:'Use global site styles',header:'Show global header',footer:'Show global footer'}))B.field(g,B.page.builder.site,key,label,'checkbox');g.append(button('Edit site settings',()=>site()));}else if(mode==='theme'){if(B.page.builder.tokens){const g=B.group(parent,'Local style defaults');for(const [key,label]of Object.entries({headingSize:'Heading size',textSize:'Body text size',sectionSpacing:'Section spacing',gap:'Element gap',buttonRadius:'Button radius',buttonX:'Button horizontal padding',buttonY:'Button vertical padding'}))B.field(g,B.page.builder.tokens,key,label,'number',{min:0,max:key==='headingSize'?160:200});}if(B.page.builder.site?.styles)parent.prepend(E('p',{class:'device-style-note'},'This page uses published global styles. Disable them in Page settings to use a local theme.'));parent.append(button('Global site styles',()=>site()));}if(node&&node.type!=='legacy')parent.append(button('Save as reusable section',()=>capture('section',node)));}
 window.DreamGridTools={images,menu,site,inspector};
 const rail=document.querySelector('.tool-rail'),spacer=rail.querySelector('.rail-spacer');for(const [label,icon,fn]of [['Sections','▧',()=>library('section')],['Images','▩',()=>images()],['Site','◈',()=>site()],['Menu','☰',()=>site('navigation')]]){const e=button('',fn,'rail-button');e.setAttribute('aria-label',label==='Site'?'Site settings':label+' library');e.title=label;e.append(E('span',{},icon),E('small',{},label));rail.insertBefore(e,spacer);}
 const templates=document.getElementById('template-dialog'),controls=E('div',{class:'tools-controls'});controls.append(button('My saved templates',()=>library('template')),button('Save this page as a template',()=>capture('template')));templates.insertBefore(controls,document.getElementById('template-list'));
 if(!B.page.id&&!B.page.builder.blocks.length)B.page.builder.site={styles:true,header:false,footer:false};B.renderInspector();
})();
