<?php
function ag_pf_forms($page){$out=array();$seen=array();$walk=function($nodes)use(&$walk,&$out,&$seen){foreach($nodes as $n){$seen[$n['id']]=true;if($n['type']==='form')$out[$n['id']]=$n;$walk($n['children']);}};$walk($page['builder']['blocks'] ?? array());$site=ag_pbl_site_live();$base=$seen;
    foreach(array('header','footer') as $role)if(!empty($page['builder']['site'][$role])&&!empty($site[$role])){try{$e=ag_pbl_get('section',$site[$role]);$seen=$base;$walk(ag_pbl_render_nodes($e,$role,$site,$seen));}catch(Throwable $e){}}return $out;
}
function ag_pf_live($pageId,$formId,$session){$p=ag_pd_load_by_id($pageId);if(!$p||empty($p['published']))throw new RuntimeException('This form is unavailable.',404);$status=ag_pd_can_view($p,(bool)$session,$session&&ag_is_admin($session),false);if($status!==200)throw new RuntimeException('Access denied.',$status);$forms=ag_pf_forms(ag_pd_normalize($p));if(!isset($forms[$formId]))throw new RuntimeException('This form is unavailable.',404);$n=$forms[$formId];if(!$n['props']['fields'])throw new RuntimeException('This form has no fields.',422);return array($p,$n);}
function ag_pf_challenge($pageId,$formId,$session){list($p,$n)=ag_pf_live($pageId,$formId,$session);$items=$_SESSION['pd_form_tokens'] ?? array();foreach($items as $k=>$item)if($item['issued']<time()-1800)unset($items[$k]);while(count($items)>=16)array_shift($items);$token=bin2hex(random_bytes(24));$items[$token]=array('page'=>$p['id'],'form'=>$formId,'issued'=>time(),'revision'=>ag_pd_revision($n));$_SESSION['pd_form_tokens']=$items;return array('token'=>$token,'waitSeconds'=>2);}
function ag_pf_submission_file($id){if(!is_string($id)||!preg_match('/^[a-f0-9]{32}$/',$id))throw new RuntimeException('Invalid submission identifier.');return ag_pd_root().'/forms/submissions/'.$id.'.json';}
function ag_pf_secret(){$file=ag_pd_root().'/forms/rate-secret.json';$doc=ag_pd_read_document($file);if(!$doc){$doc=array('key'=>bin2hex(random_bytes(32)));ag_pd_write_document($file,$doc);}return $doc['key'];}
function ag_pf_accept($pageId,$formId,$token,$raw,$trap,$session,$address){
    list($p,$n)=ag_pf_live($pageId,$formId,$session);$ticket=is_string($token)?($_SESSION['pd_form_tokens'][$token] ?? null):null;
    if(!$ticket||$ticket['page']!==$pageId||$ticket['form']!==$formId||$ticket['issued']<time()-1800||!hash_equals($ticket['revision'],ag_pd_revision($n)))throw new RuntimeException('The form changed or expired. Reload the page and try again.',409);
    if($trap!==''||time()-$ticket['issued']<2)throw new RuntimeException('Please wait a moment, then try again.',429);$values=ag_pf_values($n['props'],$raw);
    $record=ag_pd_lock(function()use($p,$n,$values,$address){$key=hash_hmac('sha256',(string)$address,ag_pf_secret());$file=ag_pd_root().'/forms/rate-limits.json';$rates=ag_pd_read_document($file) ?: array();foreach($rates as $k=>$r)if($r['start']<time()-600)unset($rates[$k]);$rate=$rates[$key] ?? array('start'=>time(),'count'=>0);if($rate['count']>=5)throw new RuntimeException('Too many messages. Please try again later.',429);if(count($rates)>=5000&&!isset($rates[$key]))throw new RuntimeException('Forms are busy. Please try again later.',429);
        if(count(glob(ag_pd_root().'/forms/submissions/*.json') ?: array())>=5000)throw new RuntimeException('The message inbox is full. Please contact the site owner another way.',503);
        $record=array('id'=>bin2hex(random_bytes(16)),'created'=>time(),'pageId'=>$p['id'],'pageTitle'=>$p['title'],'formId'=>$n['id'],'formTitle'=>$n['props']['title'],'handling'=>$n['props']['handling'],'recipient'=>$n['props']['recipient'],'fields'=>$values,'read'=>false,'archived'=>false,'delivery'=>$n['props']['handling']==='local'?'local':'pending','attempts'=>0);
        $rate['count']++;$rates[$key]=$rate;ag_pd_write_document($file,$rates);ag_pd_write_document(ag_pf_submission_file($record['id']),$record);return $record;});unset($_SESSION['pd_form_tokens'][$token]);return array('id'=>$record['id'],'message'=>$n['props']['successMessage'],'handling'=>$record['handling']);
}
function ag_pf_mail_config(){
    $get=function($key,$fallback=''){try{return function_exists('ag_dg_setting')?(ag_dg_setting($key) ?? $fallback):$fallback;}catch(Throwable $e){return $fallback;}};
    $bool=function($v){return in_array(strtolower((string)$v),array('1','true','yes','on','enabled'),true);};$root=ag_dg_root();$modes=array('None','Automatic','SslOnConnect','StartTls','StartTlsWhenAvailable');$username=trim((string)$get('SmtPropUserName'));$host=trim((string)$get('SmtpHost'));$worker=$root.'/_WEB_CONTROL/DreamGrid.EmailSender.ps1';$dll=dirname($root).'/Start.dll';
    return array('username'=>$username,'password'=>(string)$get('SmtpPassword'),'host'=>$host,'port'=>ag_pd_int($get('SmtpPort',587),587,1,65535),'secure'=>$modes[ag_pd_int($get('SSLType',3),3,0,4)],'verifyCertificate'=>$bool($get('VerifyCertCheckBox',true)),'enabled'=>$bool($get('EmailEnabled',false)),'configured'=>$username!==''&&strtolower($username)!=='loginname@somewhere.net'&&$host!==''&&is_file($worker)&&is_file($dll),'worker'=>$worker,'dll'=>$dll);
}
function ag_pf_mail_status(){$c=ag_pf_mail_config();return array('configured'=>$c['configured'],'enabled'=>$c['enabled']);}
function ag_pf_transport($record){
    $c=ag_pf_mail_config();if(!$c['enabled']||!$c['configured'])throw new RuntimeException('DreamGrid SMTP is not configured and enabled.');if(!filter_var($record['recipient'],FILTER_VALIDATE_EMAIL))throw new RuntimeException('The form notification recipient is missing.');
    $body=$record['pageTitle']." / ".$record['formTitle']."\nSubmission: ".$record['id']."\n\n";foreach($record['fields'] as $f)$body.=$f['label'].": ".$f['value']."\n\n";
    $payload=array_intersect_key($c,array_flip(array('username','password','host','port','secure','verifyCertificate')));$payload['fromName']=function_exists('ag_grid_name')?ag_grid_name():'Website';$payload['subject']=ag_pd_text('Website form: '.$record['formTitle'],180);$payload['message']=$body;$payload['recipients']=array(array('name'=>'Website messages','email'=>$record['recipient']));
    $process=@proc_open(array('powershell.exe','-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',$c['worker'],'-StartDll',$c['dll']),array(0=>array('pipe','r'),1=>array('pipe','w'),2=>array('pipe','w')),$pipes,dirname(ag_dg_root()),null,array('bypass_shell'=>true,'create_no_window'=>true));if(!is_resource($process))throw new RuntimeException('DreamGrid email worker could not be started.');
    fwrite($pipes[0],json_encode($payload,JSON_UNESCAPED_SLASHES));fclose($pipes[0]);stream_set_blocking($pipes[1],false);stream_set_blocking($pipes[2],false);$output='';$end=microtime(true)+20;$timedOut=false;
    do{$output.=stream_get_contents($pipes[1]);stream_get_contents($pipes[2]);$state=proc_get_status($process);if(!$state['running'])break;if(microtime(true)>$end){$timedOut=true;proc_terminate($process);break;}usleep(50000);}while(true);$output.=stream_get_contents($pipes[1]);fclose($pipes[1]);fclose($pipes[2]);proc_close($process);$result=json_decode(trim($output),true);
    if($timedOut||!is_array($result)||empty($result['ok']))throw new RuntimeException('Email delivery failed. The message is retained for an administrator to retry.');return true;
}
function ag_pf_delivery($id,$sender=null){
    $r=ag_pd_lock(function()use($id){$f=ag_pf_submission_file($id);$r=ag_pd_read_document($f);if(!$r)throw new RuntimeException('Message not found.');if($r['handling']==='local'||$r['delivery']==='sent')return null;if($r['delivery']==='sending'&&($r['deliveryStarted'] ?? 0)>time()-120)throw new RuntimeException('Email delivery is already running.');$r['delivery']='sending';$r['deliveryStarted']=time();$r['attempts']++;ag_pd_write_document($f,$r);return $r;});if(!$r)return;
    $error='';try{if($sender)$sender($r);else ag_pf_transport($r);}catch(Throwable $e){$error='Email delivery failed. Check DreamGrid SMTP settings and the form recipient, then retry.';}
    ag_pd_lock(function()use($id,$error){$file=ag_pf_submission_file($id);$r=ag_pd_read_document($file);if(!$r)return;$r['delivery']=$error===''?'sent':'failed';$r['deliveryError']=$error;$r['deliveryUpdated']=time();ag_pd_write_document($file,$r);});
}
function ag_pf_inbox($archived=false,$offset=0){$rows=array();foreach(glob(ag_pd_root().'/forms/submissions/*.json') ?: array() as $f){$r=ag_pd_read_document($f);if((bool)$r['archived']===(bool)$archived)$rows[]=array('file'=>$f,'created'=>$r['created']);}usort($rows,function($a,$b){return $b['created']<=>$a['created'];});$offset=ag_pd_int($offset,0,0,5000);return array('total'=>count($rows),'offset'=>$offset,'items'=>array_map(function($r){return ag_pd_read_document($r['file']);},array_slice($rows,$offset,50)),'mail'=>ag_pf_mail_status());}
function ag_pf_message_action($id,$action){if($action==='retry'){ag_pf_delivery($id);return;}ag_pd_lock(function()use($id,$action){$file=ag_pf_submission_file($id);$r=ag_pd_read_document($file);if(!$r)throw new RuntimeException('Message not found.');if($action==='read')$r['read']=true;elseif($action==='unread')$r['read']=false;elseif($action==='archive')$r['archived']=true;elseif($action==='restore')$r['archived']=false;elseif($action==='delete'){if($r['delivery']==='sending'&&($r['deliveryStarted'] ?? 0)>time()-120)throw new RuntimeException('Wait until delivery finishes.');$dest=ag_pd_root().'/forms/trash/'.$id.'.json';ag_pd_write_document($dest,$r);if(!unlink($file))throw new RuntimeException('Could not remove the message.');return;}else throw new RuntimeException('Unknown message action.');ag_pd_write_document($file,$r);});}
