<?php
function ag_ps_inventory(){ $out=array();foreach(ag_pd_editor_pages() as $raw){$p=ag_pd_normalize($raw);$images=array();foreach(ag_pd_page_images($p) as $name){$path=ag_pd_asset_path($p['id'],$name);if($path)$images[]=array('name'=>$name,'sha256'=>hash_file('sha256',$path));}$out[]=array('id'=>$p['id'],'title'=>$p['title'],'published'=>$raw['published'],'hasDraft'=>$raw['hasDraft'],'images'=>$images);}return $out; }
function ag_ps_spec($raw){
    if(!is_array($raw)||!is_array($raw['ids'] ?? null)||count($raw['ids'])<1||count($raw['ids'])>100)throw new RuntimeException('Choose between 1 and 100 saved pages.');$ids=array_values(array_unique($raw['ids']));foreach($ids as $id)if(!ag_pd_page_file($id)||!ag_pd_edit_page($id))throw new RuntimeException('A selected page is unavailable.');$mode=ag_pd_enum($raw['mode'] ?? '',array('text','url','image'),'');if(!$mode)throw new RuntimeException('Choose a replacement type.');
    $out=array('ids'=>$ids,'mode'=>$mode,'caseSensitive'=>!empty($raw['caseSensitive']),'find'=>ag_pd_text($raw['find'] ?? '',300),'replace'=>ag_pd_text($raw['replace'] ?? '',3000));if($mode!=='image'&&$out['find']==='')throw new RuntimeException('Enter text or a URL to find.');
    if($mode==='image'){foreach(array('source','target') as $role){$id=$raw[$role.'Page'] ?? '';$name=$raw[$role.'File'] ?? '';$p=ag_pd_edit_page($id);$path=ag_pd_asset_path($id,$name);if(!$p||!$path||!in_array($name,ag_pd_page_images($p),true))throw new RuntimeException('Choose a saved source and replacement image.');$info=@getimagesize($path);if(!$info||!in_array($info['mime'] ?? '',array('image/jpeg','image/png','image/gif','image/webp'),true)||filesize($path)>8388608)throw new RuntimeException('Choose a supported replacement image.');$out[$role.'Page']=$id;$out[$role.'File']=$name;$out[$role.'Hash']=hash_file('sha256',$path);}}
    return $out;
}
function ag_ps_change($page,$spec){
    $p=ag_pd_normalize($page);$legacy=!isset($p['builder']);$legacyLocked=false;$inspect=function($nodes,$locked=false)use(&$inspect,&$legacy,&$legacyLocked){foreach($nodes as $n){$lockedHere=$locked||!empty($n['locked']);if($n['type']==='legacy'){$legacy=true;$legacyLocked=$legacyLocked||$lockedHere;}$inspect($n['children'],$lockedHere);}};if(isset($p['builder']))$inspect($p['builder']['blocks']);$count=0;$skipped=0;$samples=array();$imageFiles=array();$textKeys=array('title','description','shareTitle','shareDescription','imageAlt','text','subtitle','label','alt','kicker','brand','attribution','buttonLabel','linkLabel','menuLabel','question','answer','value','successMessage','placeholder','help','options');$urlKeys=array('url','buttonUrl','videoUrl','linkUrl');
    $edit=function(&$value,$key,$locked=false)use(&$edit,$p,$spec,&$count,&$skipped,&$samples,&$imageFiles,$textKeys,$urlKeys){if(is_array($value)){foreach($value as $k=>&$v)$edit($v,is_int($k)?$key:$k,$locked);unset($v);return;}if(!is_string($value))return;
        if($spec['mode']==='image'){if(!in_array($key,array('image','backgroundImage'),true)||!ag_pd_image_name($value))return;$path=ag_pd_asset_path($p['id'],$value);if(!$path||hash_file('sha256',$path)!==$spec['sourceHash'])return;if($locked){$skipped++;return;}$imageFiles[$value]=true;$count++;if(count($samples)<5)$samples[]=array('field'=>$key,'before'=>$value,'after'=>$spec['targetFile']);return;}
        if(!in_array($key,$spec['mode']==='url'?$urlKeys:$textKeys,true))return;$occurrences=0;$next=$spec['caseSensitive']?str_replace($spec['find'],$spec['replace'],$value,$occurrences):str_ireplace($spec['find'],$spec['replace'],$value,$occurrences);if(!$occurrences||$next===$value)return;if($locked){$skipped+=$occurrences;return;}$count+=$occurrences;if(count($samples)<5)$samples[]=array('field'=>$key,'before'=>ag_pd_text($value,160),'after'=>ag_pd_text($next,160));$value=$next;
    };
    foreach($p as $key=>&$value)if($key!=='builder'&&(!in_array($key,array('cards','backgroundImage'),true)||$legacy))$edit($value,$key,in_array($key,array('cards','backgroundImage'),true)&&$legacyLocked);unset($value);
    if(isset($p['builder'])){$edit($p['builder']['theme'],'theme');$walk=function(&$nodes,$locked=false,$panels=false)use(&$walk,$edit){foreach($nodes as &$n){$protected=$locked||!empty($n['locked']);if($panels)$edit($n['name'],'label',$protected);$edit($n['props'],'props',$protected);$walk($n['children'],$protected,in_array($n['type'],array('tabs','accordion'),true));}unset($n);};$walk($p['builder']['blocks']);}
    $candidate=$p;$p=ag_pd_normalize($p);if(json_encode($candidate)!==json_encode($p))throw new RuntimeException('A replacement exceeds a field limit or cannot be represented. Use a shorter replacement.');return array('page'=>$p,'count'=>$count,'skipped'=>$skipped,'samples'=>$samples,'imageFiles'=>array_keys($imageFiles),'legacy'=>$legacy,'legacyLocked'=>$legacyLocked);
}
function ag_ps_preview($raw){return ag_pd_lock(function()use($raw){$spec=ag_ps_spec($raw);$rows=array();$total=0;foreach($spec['ids'] as $id){$p=ag_pd_edit_page($id);$r=ag_ps_change($p,$spec);$rows[]=array('id'=>$id,'title'=>$p['title'],'revision'=>ag_pd_editor_revision($id),'count'=>$r['count'],'skipped'=>$r['skipped'],'samples'=>$r['samples']);$total+=$r['count'];}return array('spec'=>$spec,'rows'=>$rows,'total'=>$total,'note'=>'Edits become private drafts. Locked elements are skipped. Shared site sections, saved templates and history are outside this operation.');});}
function ag_ps_apply($raw,$expected){return ag_pd_lock(function()use($raw,$expected){$spec=ag_ps_spec($raw);if(!is_array($expected))throw new RuntimeException('Preview the replacement first.');if($spec['mode']==='image'&&(($raw['sourceHash'] ?? '')!==$spec['sourceHash']||($raw['targetHash'] ?? '')!==$spec['targetHash']))throw new RuntimeException('An image changed since preview. Preview again.');$changes=array();
    foreach($spec['ids'] as $id){$revision=ag_pd_editor_revision($id);if(!isset($expected[$id])||!is_string($expected[$id])||!hash_equals($revision,$expected[$id]))throw new RuntimeException('A selected page changed. Preview again before replacing.');$before=ag_pd_edit_page($id);$r=ag_ps_change($before,$spec);if($r['count'])$changes[$id]=array('before'=>$before,'result'=>$r,'draft'=>ag_pd_load_draft($id));}
    if(!$changes)throw new RuntimeException('No changes remain to apply.');$batch=bin2hex(random_bytes(16));$journal=ag_pd_root().'/site-edits/'.$batch.'.json';$added=array();$history=array();$written=array();$entries=array();foreach($changes as $id=>$c)$entries[]=array('pageId'=>$id,'before'=>$c['before'],'previousDraft'=>$c['draft'],'replacements'=>$c['result']['count']);ag_pd_write_document($journal,array('id'=>$batch,'created'=>time(),'status'=>'preparing','entries'=>$entries));
    try{foreach($changes as $id=>$c){$p=$c['result']['page'];if($spec['mode']==='image'){$path=ag_pd_asset_path($spec['targetPage'],$spec['targetFile']);$bytes=file_get_contents($path);$name=bin2hex(random_bytes(12)).'.'.pathinfo($spec['targetFile'],PATHINFO_EXTENSION);$dest=ag_pd_asset_dir_for_page($id,true).'/'.$name;$added[]=$dest;if(file_put_contents($dest,$bytes,LOCK_EX)!==strlen($bytes))throw new RuntimeException('Could not store the replacement image.');$old=$c['result']['imageFiles'];$map=function(&$v,$key='')use(&$map,$old,$name){if(is_array($v)){foreach($v as $k=>&$item)$map($item,is_int($k)?$key:$k);unset($item);}elseif(is_string($v)&&in_array($key,array('image','backgroundImage'),true)&&in_array($v,$old,true))$v=$name;};
                    // Preserve locked subtrees even when they share the same image.
                    foreach($p as $k=>&$v)if($k!=='builder'&&(!in_array($k,array('cards','backgroundImage'),true)||($c['result']['legacy']&&!$c['result']['legacyLocked'])))$map($v,$k);unset($v);if(isset($p['builder'])){$map($p['builder']['theme']);$walk=function(&$nodes,$locked=false)use(&$walk,$map){foreach($nodes as &$n){$protected=$locked||!empty($n['locked']);if(!$protected)$map($n['props']);$walk($n['children'],$protected);}unset($n);};$walk($p['builder']['blocks']);}}
            $p['updated']=time();$p=ag_pd_normalize($p);$token=ag_pd_record_revision($p,'site-replace');$history[]=ag_pd_history_file($id,$token);$written[]=$id;ag_pd_write_document(ag_pd_draft_file($id),$p);}
        ag_pd_write_document($journal,array('id'=>$batch,'created'=>time(),'status'=>'saved-drafts','entries'=>$entries));
    }catch(Throwable $e){foreach($written as $id){if($changes[$id]['draft'])ag_pd_write_document(ag_pd_draft_file($id),$changes[$id]['draft']);else @unlink(ag_pd_draft_file($id));}foreach(array_merge($added,$history) as $f)@unlink($f);ag_pd_write_document($journal,array('id'=>$batch,'created'=>time(),'status'=>'rolled-back','entries'=>$entries));throw $e;}
    return array('batch'=>$batch,'pages'=>count($changes),'message'=>'Replacement saved as private drafts. Review and publish each page when ready.');});}
function ag_ps_scan($scope,$host=''){if(!in_array($scope,array('drafts','published'),true))throw new RuntimeException('Choose draft or published pages.');$pages=$scope==='drafts'?ag_pd_editor_pages():ag_pd_list_pages();$reports=array();$total=0;foreach($pages as $p){if($scope==='published'&&empty($p['published']))continue;try{$report=ag_pc_check($p,array(),$host);$reports[]=array('id'=>$p['id'],'title'=>$p['title'],'slug'=>$p['slug'],'published'=>!empty($p['published']),'errors'=>$report['errors'],'warnings'=>$report['warnings'],'issues'=>$report['issues'],'externalLinks'=>$report['externalLinksSkipped']);$total+=count($report['issues']);}catch(Throwable $e){$reports[]=array('id'=>$p['id'],'title'=>$p['title'],'errors'=>1,'warnings'=>0,'issues'=>array(array('code'=>'page_unreadable','severity'=>'error','message'=>'This page could not be checked. Open it and inspect its saved content.')));$total++;}}
    return array('scope'=>$scope,'pages'=>count($reports),'findings'=>$total,'reports'=>$reports,'note'=>'Read-only scan of saved pages, images, internal links and anchors. External websites and dynamic route responses are not fetched.');
}
