<?php
function ag_ti_scan($path) {
    if(!is_file($path)||filesize($path)>33554432)throw new RuntimeException('Choose a template ZIP of 32 MB or smaller.');
    $zip=new AgTemplateZip();if($zip->open($path)!==true)throw new RuntimeException('The template ZIP could not be opened.');
    try{$files=array();$pages=array();$notices=array();$total=0;$names=array();if($zip->numFiles>500)throw new RuntimeException('The ZIP contains more than 500 entries.');
        for($i=0;$i<$zip->numFiles;$i++){$s=$zip->statIndex($i);$name=$s['name'];if($name===''||preg_match('#(^/|^[a-z]:|\\\\|\x00|(^|/)\.\.(/|$))#i',$name))throw new RuntimeException('The ZIP contains an unsafe file path.');$name=preg_replace('#/+#','/',preg_replace('#^(\./)+#','',$name));$name=str_replace('/./','/',$name);$key=strtolower(rtrim($name,'/'));if(isset($names[$key]))throw new RuntimeException('The ZIP contains duplicate file names.');$names[$key]=true;$os=0;$attrs=0;if($zip->getExternalAttributesIndex($i,$os,$attrs)&&(($attrs>>16)&0170000)===0120000)throw new RuntimeException('ZIP symbolic links are not supported.');
            $size=$s['size'];if(($total+=$size)>83886080||$size>8388608||($size>1048576&&$size/max(1,$s['comp_size'])>200))throw new RuntimeException('The ZIP expands beyond the supported size limits.');if(!empty($s['encryption_method']))throw new RuntimeException('Encrypted ZIP entries are not supported.');if(substr($name,-1)==='/')continue;
            $ext=strtolower(pathinfo($name,PATHINFO_EXTENSION));$files[$name]=array('index'=>$i,'size'=>$size,'ext'=>$ext);if(in_array($ext,array('html','htm'),true)){$pages[]=$name;if($size>2097152)throw new RuntimeException('An HTML page exceeds 2 MB.');}elseif(!in_array($ext,array('css','jpg','jpeg','png','gif','webp','txt','md'),true))$notices['unsupported-files']='Scripts, fonts, SVGs and server-side files are not executed or installed. The original ZIP is retained privately after import.';
        }if(!$pages)throw new RuntimeException('No HTML pages were found. Use an HTML website template ZIP, rather than a WordPress theme.');sort($pages);return array('files'=>$files,'pages'=>$pages,'notices'=>array_values($notices));
    }finally{$zip->close();}
}
function ag_ti_resolve($base,$url) {
    $parts=@parse_url(trim($url));if($parts===false||isset($parts['scheme'])||isset($parts['host']))return null;$path=rawurldecode($parts['path'] ?? '');if(strpos($path,"\0")!==false||strpos($path,'\\')!==false)return null;
    $joined=substr($path,0,1)==='/'?ltrim($path,'/'):(dirname($base)==='.'?'':dirname($base).'/').$path;$out=array();foreach(explode('/',$joined) as $part){if($part===''||$part==='.')continue;if($part==='..'){if(!$out)return null;array_pop($out);}else $out[]=$part;}return implode('/',$out);
}
function ag_ti_dir(){return ag_pd_root().'/template-import-staging';}
function ag_ti_stage_file($token,$ext){if(!is_string($token)||!preg_match('/^[a-f0-9]{32}$/',$token))throw new RuntimeException('Invalid import token.');return ag_ti_dir().'/'.$token.'.'.$ext;}
function ag_ti_owner(){return ag_pd_editor_namespace();}
function ag_ti_stage($path,$name){$scan=ag_ti_scan($path);$owner=ag_ti_owner();$count=0;foreach(glob(ag_ti_dir().'/*.json') ?: array() as $file){$old=ag_pd_read_document($file);if(($old['owner'] ?? '')===$owner){if(($old['created'] ?? 0)<time()-7200){@unlink(substr($file,0,-5).'.zip');@unlink($file);}else $count++;}}if($count>=3)throw new RuntimeException('Close an earlier template import before uploading another.');
    $token=bin2hex(random_bytes(16));$meta=array('owner'=>$owner,'created'=>time(),'name'=>ag_pd_text(basename(str_replace('\\','/',$name)),160),'sha256'=>hash_file('sha256',$path),'scan'=>$scan);$json=ag_ti_stage_file($token,'json');if(!is_dir(ag_ti_dir())&&!mkdir(ag_ti_dir(),0700,true))throw new RuntimeException('Template staging is unavailable.');$dest=ag_ti_stage_file($token,'zip');if(!copy($path,$dest))throw new RuntimeException('The template upload could not be staged.');try{ag_pd_write_document($json,$meta);}catch(Throwable $e){@unlink($dest);throw $e;}return array('token'=>$token,'pages'=>$scan['pages'],'notices'=>$scan['notices'],'name'=>$meta['name']);
}
function ag_ti_upload($upload){if(!$upload||($upload['error'] ?? -1)!==UPLOAD_ERR_OK||!is_uploaded_file($upload['tmp_name'] ?? ''))throw new RuntimeException('ZIP upload failed or exceeds the server limit.');return ag_ti_stage($upload['tmp_name'],$upload['name'] ?? 'Template ZIP');}
function ag_ti_read($token){$meta=ag_pd_read_document(ag_ti_stage_file($token,'json'));if(!$meta||!hash_equals($meta['owner'],ag_ti_owner()))throw new RuntimeException('This template import is unavailable to the current administrator.');if($meta['created']<time()-7200)throw new RuntimeException('The template preview expired. Upload the ZIP again.');if(!is_file(ag_ti_stage_file($token,'zip'))||!hash_equals($meta['sha256'],hash_file('sha256',ag_ti_stage_file($token,'zip'))))throw new RuntimeException('The staged ZIP changed. Upload it again.');return $meta;}
function ag_ti_discard($token){ag_ti_read($token);@unlink(ag_ti_stage_file($token,'zip'));@unlink(ag_ti_stage_file($token,'json'));}
