<?php
function ag_ti_anchor($value){$slug=ag_pd_slug($value);return $slug!==''&&!preg_match('/^[a-z]/i',$slug)?'section-'.$slug:$slug;}
function ag_ti_declarations($text){$out=array();foreach(explode(';',$text) as $part){$p=explode(':',$part,2);if(count($p)===2)$out[strtolower(trim($p[0]))]=trim(preg_replace('/\s*!important\s*$/i','',$p[1]));}return $out;}
function ag_ti_selector($node,$selector){$parts=preg_split('/\s+/',trim($selector));$match=function($el,$simple){if(!$el instanceof DOMElement||!preg_match('/^(?:[a-z][a-z0-9-]*|\*)?(?:[.#][a-z0-9_-]+)*$/i',$simple))return false;preg_match('/^[a-z][a-z0-9-]*/i',$simple,$tag);if($tag&&strcasecmp($el->tagName,$tag[0])!==0)return false;preg_match_all('/([.#])([a-z0-9_-]+)/i',$simple,$bits,PREG_SET_ORDER);foreach($bits as $bit){if($bit[1]==='#'&&$el->getAttribute('id')!==$bit[2])return false;if($bit[1]==='.'&&!in_array($bit[2],preg_split('/\s+/',trim($el->getAttribute('class'))),true))return false;}return true;};
    if(!$parts||!$match($node,array_pop($parts)))return false;$parent=$node->parentNode;while($parts){$simple=array_pop($parts);while($parent instanceof DOMElement&&!$match($parent,$simple))$parent=$parent->parentNode;if(!$parent instanceof DOMElement)return false;$parent=$parent->parentNode;}return true;
}
function ag_ti_css_rules($text,$base,&$notices){$text=preg_replace('#/\*.*?\*/#s','',$text);$clean='';$len=strlen($text);for($i=0;$i<$len;$i++){if($text[$i]==='@'){$notices['css-advanced']='Media queries, font imports and CSS at-rules need manual recreation in native device styles.';$depth=0;for(;$i<$len;$i++){if($text[$i]==='{')$depth++;elseif($text[$i]==='}'&&--$depth===0)break;elseif($text[$i]===';'&&$depth===0)break;}continue;}$clean.=$text[$i];}
    preg_match_all('/([^{}]+)\{([^{}]*)\}/',$clean,$matches,PREG_SET_ORDER);$rules=array();foreach($matches as $m)foreach(explode(',',$m[1]) as $selector){$selector=trim($selector);if(strlen($selector)>180||!preg_match('/^[a-z0-9_.*#\s-]+$/i',$selector)){$notices['selectors']='Complex and interactive CSS selectors are omitted; review the native conversion.';continue;}$rules[]=array('selector'=>$selector,'props'=>ag_ti_declarations($m[2]),'base'=>$base,'rank'=>substr_count($selector,'#')*100+substr_count($selector,'.')*10+preg_match_all('/(?:^|\s)[a-z]/i',$selector));if(count($rules)>3000)throw new RuntimeException('The stylesheet is too complex for native conversion.');}return $rules;
}
function ag_ti_color($value){$v=strtolower(trim($value));$names=array('white'=>'#ffffff','black'=>'#000000','red'=>'#ff0000','blue'=>'#0000ff','green'=>'#008000','gray'=>'#808080','grey'=>'#808080','yellow'=>'#ffff00','orange'=>'#ffa500','transparent'=>'transparent');if(isset($names[$v]))return $names[$v];if(preg_match('/^#[a-f0-9]{3}(?:[a-f0-9]{3})?$/i',$v))return $v;if(preg_match('/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)/',$v,$m))return sprintf('#%02x%02x%02x',min(255,$m[1]),min(255,$m[2]),min(255,$m[3]));return null;}
function ag_ti_px($value){if(!preg_match('/^(-?\d+(?:\.\d+)?)(px|rem|em|pt)?$/i',trim($value),$m))return null;$unit=strtolower($m[2] ?? 'px');return (float)$m[1]*($unit==='rem'||$unit==='em'?16:($unit==='pt'?4/3:1));}
function ag_ti_style($css,&$notices){$s=array();foreach(array('color'=>'color','background-color'=>'background','border-color'=>'borderColor') as $from=>$to)if(isset($css[$from])&&($v=ag_ti_color($css[$from]))!==null)$s[$to]=$v;if(isset($css['background'])&&($v=ag_ti_color($css['background']))!==null)$s['background']=$v;
    foreach(array('font-size'=>'fontSize','margin-top'=>'marginTop','margin-bottom'=>'marginBottom','border-radius'=>'radius','gap'=>'gap','min-height'=>'minHeight','height'=>'height','border-width'=>'borderWidth') as $from=>$to)if(isset($css[$from])&&($v=ag_ti_px($css[$from]))!==null)$s[$to]=$v;
    if(isset($css['padding'])){$parts=preg_split('/\s+/',trim($css['padding']));$values=array_map('ag_ti_px',$parts);if(!in_array(null,$values,true)){$s['padding']=$values[count($values)===1?0:1];$s['paddingY']=$values[0];}}
    if(isset($css['padding-top'])&&($v=ag_ti_px($css['padding-top']))!==null)$s['paddingY']=$v;if(isset($css['padding-left'])&&($v=ag_ti_px($css['padding-left']))!==null)$s['padding']=$v;
    if(isset($css['text-align'])&&in_array($css['text-align'],array('left','center','right'),true))$s['align']=$css['text-align'];if(isset($css['font-weight']))$s['bold']=$css['font-weight']==='bold'||(is_numeric($css['font-weight'])&&$css['font-weight']>=600);if(isset($css['font-style']))$s['italic']=$css['font-style']==='italic';if(isset($css['box-shadow']))$s['shadow']=$css['box-shadow']==='none'?'none':'soft';
    if(isset($css['font-family'])){$family=strtolower(trim(explode(',',$css['font-family'])[0]," \t\r\n\"'"));$found=false;foreach(ag_pd_font_catalog() as $key=>$font)if(strtolower($font['label'])===$family){$s['font']=$key;$found=true;break;}if(!$found)$notices['fonts']='Unavailable fonts use the builder default. External font downloads are not made.';}
    if(($css['display'] ?? '')==='none')$s['hideDesktop']=$s['hideTablet']=$s['hideMobile']=true;
    if(isset($css['max-width'])&&($v=ag_ti_px($css['max-width']))!==null)$s['width']=$v<=650?'narrow':($v<=950?'medium':'wide');
    return ag_pb_style($s);
}
function ag_ti_convert($path,$selected){$scan=ag_ti_scan($path);if(!in_array($selected,$scan['pages'],true))throw new RuntimeException('Choose an HTML page listed in this ZIP.');$zip=new AgTemplateZip();if($zip->open($path)!==true)throw new RuntimeException('The ZIP is unavailable.');
    try{$read=function($name)use($zip,$scan){if(!isset($scan['files'][$name]))return null;$f=$scan['files'][$name];$bytes=$zip->getFromIndex($f['index']);if(!is_string($bytes)||strlen($bytes)!==$f['size'])throw new RuntimeException('A ZIP entry could not be read.');return $bytes;};$html=$read($selected);if(!class_exists('DOMDocument'))throw new RuntimeException('Native conversion requires the PHP DOM extension.');$doc=new DOMDocument();$old=libxml_use_internal_errors(true);try{$doc->loadHTML('<?xml encoding="UTF-8">'.$html,LIBXML_NONET|LIBXML_NOERROR|LIBXML_NOWARNING);}finally{libxml_clear_errors();libxml_use_internal_errors($old);}if($doc->getElementsByTagName('*')->length>2500)throw new RuntimeException('This HTML page is too large for native conversion.');$body=$doc->getElementsByTagName('body')->item(0);if(!$body)throw new RuntimeException('No page body was found.');
        $notices=array();foreach($scan['notices'] as $v)$notices[$v]=$v;$notices['css-scope']='Basic colours, fonts, spacing and grid/flex columns are mapped. Gradients, transforms, positioning and advanced CSS need manual adjustments.';$notices['approximation']='This is an editable native conversion, not an exact copy. Review layout and device styles before publishing.';$rules=array();$cssTotal=0;
        foreach($doc->getElementsByTagName('link') as $link)if(stripos($link->getAttribute('rel'),'stylesheet')!==false){$file=ag_ti_resolve($selected,$link->getAttribute('href'));if($file===null||!isset($scan['files'][$file])||$scan['files'][$file]['ext']!=='css'){$notices['css-missing']='Some stylesheets are missing or external and were not fetched.';continue;}$css=$read($file);if(($cssTotal+=strlen($css))>4194304)throw new RuntimeException('Stylesheets exceed the 4 MB conversion limit.');$rules=array_merge($rules,ag_ti_css_rules($css,$file,$notices));}
        foreach($doc->getElementsByTagName('style') as $style){if(($cssTotal+=strlen($style->textContent))>4194304)throw new RuntimeException('Stylesheets exceed the conversion limit.');$rules=array_merge($rules,ag_ti_css_rules($style->textContent,$selected,$notices));}if(count($rules)>3000)throw new RuntimeException('There are too many CSS rules.');
        $assets=array();$imageMap=array();$bytesTotal=0;$image=function($uri,$base)use($scan,$read,&$assets,&$imageMap,&$bytesTotal,&$notices){$file=ag_ti_resolve($base,$uri);if($file===null||!isset($scan['files'][$file])){$notices['images-missing']='Missing or external images were left as placeholders. No remote images were downloaded.';return ''; }if(isset($imageMap[$file]))return $imageMap[$file];$bytes=$read($file);$info=@getimagesizefromstring($bytes);$types=array('image/png'=>'png','image/jpeg'=>'jpg','image/gif'=>'gif','image/webp'=>'webp');$ext=$types[$info['mime'] ?? ''] ?? '';if(!$ext){$notices['images-unsupported']='SVG or unsupported images were omitted. Replace them with PNG, JPEG, GIF or WebP.';return ''; }if(($bytesTotal+=strlen($bytes))>16777216)throw new RuntimeException('Selected page images exceed 16 MB.');$name=bin2hex(random_bytes(12)).'.'.$ext;$imageMap[$file]=$name;$assets[$name]=array('data'=>base64_encode($bytes),'sha256'=>hash('sha256',$bytes));return $name;};
        $computed=function($el,$inherit)use($rules,&$notices){$css=array();foreach(array('color','font-family','font-size','font-weight','font-style','text-align') as $key)if(isset($inherit[$key]))$css[$key]=$inherit[$key];$rank=array();$base='';foreach($rules as $r)if(ag_ti_selector($el,$r['selector']))foreach($r['props'] as $key=>$value)if(!isset($rank[$key])||$r['rank']>=$rank[$key]){$css[$key]=$value;$rank[$key]=$r['rank'];if($key==='background-image'||$key==='background')$base=$r['base'];}foreach(ag_ti_declarations($el->getAttribute('style')) as $k=>$v){$css[$k]=$v;if($k==='background-image'||$k==='background')$base='';}return array($css,$base);};
        $count=0;$make=function($type,$props,$style,$children=array(),$name='')use(&$count){if(++$count>240)throw new RuntimeException('The conversion exceeds 240 editable elements. Choose a simpler page.');return array('id'=>bin2hex(random_bytes(6)),'type'=>$type,'name'=>$name ?: ucfirst($type),'props'=>$props,'style'=>$style,'children'=>$children);};
        $topAnchor=ag_ti_anchor($body->getAttribute('id')) ?: 'imported-top';$link=function($url)use($selected,$topAnchor,&$notices){$url=trim($url);if($url==='')return '';if(substr($url,0,1)==='#')return '#'.(ag_ti_anchor(rawurldecode(substr($url,1))) ?: $topAnchor);if(preg_match('#^(https?://|mailto:|hop://)#i',$url))return ag_pb_link($url);$parts=@parse_url($url);$file=ag_ti_resolve($selected,$url);if($file===$selected)return '#'.(!empty($parts['fragment'])?ag_ti_anchor(rawurldecode($parts['fragment'])):$topAnchor);$notices['local-links']='Links to other template pages or local files need to be connected to imported DreamGrid pages; their buttons were disabled.';return '';};
        $walk=function($el,$depth,$inherit=array())use(&$walk,$computed,$make,$image,$link,$selected,&$notices){if($el instanceof DOMText){$text=trim(preg_replace('/\s+/u',' ',$el->textContent));return $text!==''?array($make('text',array('text'=>$text),ag_ti_style($inherit,$notices))):array();}if(!$el instanceof DOMElement)return array();$tag=strtolower($el->tagName);if(in_array($tag,array('script','iframe','object','embed','svg','canvas','style','link','meta','input','select','textarea','button'),true)){$notices['interactive']='Scripts, embedded content, forms and custom interactions were omitted and need native replacements.';return array();}if($tag==='form'){$notices['forms']='Forms were converted to visible labels/text only. Submission handling was not imported.';}
            list($css,$cssBase)=$computed($el,$inherit);$style=ag_ti_style($css,$notices);$anchor=$el->hasAttribute('id')?ag_ti_anchor($el->getAttribute('id')):'';$props=$anchor!==''?array('anchor'=>$anchor):array();$text=trim(preg_replace('/\s+/u',' ',$el->textContent));$name=$anchor ?: ucfirst($tag);
            if(preg_match('/^h[1-6]$/',$tag)){if(!isset($style['fontSize']))$style['fontSize']=$tag==='h1'?48:($tag==='h2'?36:24);$nodes=array($make('heading',array_merge($props,array('text'=>$text,'tag'=>$tag)),$style,array(),$name));foreach($el->getElementsByTagName('a') as $a){$notices['inline-links']='Inline links were converted into separate editable buttons.';$nodes=array_merge($nodes,$walk($a,$depth,$css));}return $nodes;}
            if($tag==='img')return array($make('image',array_merge($props,array('image'=>$image($el->getAttribute('src'),$selected),'alt'=>$el->getAttribute('alt'))),$style,array(),$el->getAttribute('alt') ?: 'Imported image'));
            if($tag==='a'){$nodes=array();foreach($el->getElementsByTagName('img') as $img)$nodes=array_merge($nodes,$walk($img,$depth,$css));$url=$link($el->getAttribute('href'));$nodes[]=$make('button',array_merge($props,array('label'=>$text ?: ($el->getAttribute('title') ?: 'Open link'),'url'=>$url,'disabled'=>$url==='','newTab'=>$el->getAttribute('target')==='_blank')),$style,array(),$name);return $nodes;}
            if($tag==='br'||$tag==='hr')return $tag==='hr'?array($make('divider',$props,$style)):array();
            if($tag==='table'){$rows=array();foreach($el->getElementsByTagName('tr') as $row){$cells=array();foreach($row->childNodes as $cell)if($cell instanceof DOMElement)$cells[]=trim($cell->textContent);$rows[]=implode(' · ',$cells);}$notices['tables']='Tables were converted to editable text rows.';return array($make('text',array_merge($props,array('text'=>implode("\n",$rows))),$style));}
            if($tag==='p'||$tag==='li'||in_array($tag,array('span','strong','em','small','label'),true)){$hasBlock=false;foreach($el->getElementsByTagName('*') as $child)if(in_array(strtolower($child->tagName),array('img','div','p','section','h1','h2','h3'),true))$hasBlock=true;if(!$hasBlock){$nodes=$text!==''?array($make('text',array_merge($props,array('text'=>($tag==='li'?'• ':'').$text)),$style,array(),$name)):array();foreach($el->getElementsByTagName('a') as $a){$notices['inline-links']='Inline links were converted into separate editable buttons.';$nodes=array_merge($nodes,$walk($a,$depth,$css));}return $nodes;}}
            $children=array();foreach($el->childNodes as $child)$children=array_merge($children,$walk($child,min(6,$depth+1),$css));if(!$children)return array();if($depth>=6){$notices['depth']='Deep wrapper containers were flattened to fit the builder nesting limit.';if($anchor!=='')$children[0]['props']['anchor']=$anchor;return $children;}
            $style=array_merge(array('padding'=>0,'paddingY'=>0,'gap'=>12),$style);$type='section';if(in_array($css['display'] ?? '',array('grid','flex'),true)&&count($children)>1){$type='columns';$columns=0;if(isset($css['grid-template-columns'])&&preg_match('/repeat\(\s*(\d+)/',$css['grid-template-columns'],$m))$columns=(int)$m[1];$style['columns']=max(1,min(6,$columns ?: count($children)));$style['tabletColumns']=min(2,$style['columns']);$style['mobileColumns']=1;}
            if(preg_match('/url\(\s*["\']?([^"\')]+)["\']?\s*\)/',$css['background-image'] ?? $css['background'] ?? '',$bg)){$props['image']=$image($bg[1],$cssBase ?: $selected);if($type==='columns'){$notices['background-columns']='Some column backgrounds need to be reapplied on a containing section.';unset($props['image']);}}
            return array($make($type,$props,$style,$children,$name));
        };
        $blocks=$walk($body,0);if(!$blocks)throw new RuntimeException('No editable page content was found.');$blocks[0]['props']['anchor']=$topAnchor;$title=trim($doc->getElementsByTagName('title')->item(0)->textContent ?? '') ?: pathinfo($selected,PATHINFO_FILENAME);$p=ag_pd_default_page();$p['id']=str_repeat('0',16);$p['title']=$title;$p['builder']=array('version'=>1,'theme'=>array(),'blocks'=>$blocks);$p=ag_pd_normalize($p);$used=ag_pd_page_images($p);$assets=array_intersect_key($assets,array_flip($used));$package=array('format'=>'dreamgrid-page','version'=>1,'page'=>$p,'assets'=>$assets);$json=json_encode($package,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);if(strlen($json)>ag_pd_package_limit())throw new RuntimeException('The converted page exceeds the portable package size limit.');
        $licenses=array();foreach($scan['files'] as $name=>$info)if(in_array($info['ext'],array('txt','md'),true)&&preg_match('/(licen[cs]e|readme|copyright)/i',$name)){$license=$read($name);if(!preg_match('//u',$license)){$license=iconv('Windows-1252','UTF-8//IGNORE',$license);}$licenses[$name]=ag_pd_text($license,50000);if(count($licenses)>=8)break;}
        $preview=ag_pd_render($p,true);foreach($assets as $name=>$asset){$url=ag_pd_asset_url($p['id'],$name);$uri='data:image/'.(substr($name,-3)==='jpg'?'jpeg':(substr($name,-4)==='webp'?'webp':substr($name,-3))).';base64,'.$asset['data'];$preview=str_replace(array($url,ag_pd_h($url)),$uri,$preview);}
        return array('package'=>$package,'html'=>$preview,'notices'=>array_values($notices),'licenses'=>$licenses,'elements'=>$count,'images'=>count($assets),'title'=>$p['title'],'selected'=>$selected);
    }finally{$zip->close();}
}
