<?php
// Original system content: identifiers, never installation paths or user artwork.
function ag_sd_artwork_library() {
    $names=array('classic'=>'Classic / Elegant','ocean'=>'Ocean / Coastal','forest'=>'Forest / Nature','christmas'=>'Christmas','halloween'=>'Halloween','easter'=>'Easter','spring'=>'Spring','summer'=>'Summer / Beach','autumn'=>'Autumn','community'=>'Community','marketplace'=>'Marketplace','fantasy'=>'Fantasy / Roleplay','festival'=>'Events / Festival','abstract'=>'Modern Dark','minimal'=>'Modern Light');
    $out=array();foreach($names as $id=>$name){$path=dirname(__DIR__,2).'/site-design/artwork/'.$id.'.png';$out[$id]=array('name'=>$name,'url'=>'/Other/site-design/artwork/'.$id.'.png'.(is_file($path)?'?v='.filemtime($path):''),'path'=>$path);}return $out;
}
function ag_sd_treatments() { return array('plain'=>'Simple','light'=>'Open light','classic'=>'Gilded editorial','coastal'=>'Coastal glass','botanical'=>'Botanical retreat','festive'=>'Festive ornaments','haunted'=>'Moonlit drama','easter'=>'Pastel Easter','spring'=>'Soft spring','sunny'=>'Sunlit resort','harvest'=>'Warm harvest','friendly'=>'Community circles','editorial'=>'Market editorial','fantasy'=>'Storybook night','festival'=>'Festival lights','modern'=>'Modern geometry','minimal'=>'Quiet minimal'); }
function ag_sd_theme_content() {
    return array(
        'light'=>array('description'=>'Open light architecture, frosted glass and generous rounded cards.','art'=>'minimal','treatment'=>'light','font'=>'segoe-ui','radius'=>16,'button'=>'rounded'),
        'classic-gold'=>array('description'=>'Charcoal architecture, brushed gold and editorial elegance.','art'=>'classic','treatment'=>'classic','font'=>'georgia','radius'=>4,'button'=>'square'),
        'ocean-blue'=>array('description'=>'Turquoise coastal depth, luminous glass and airy spacing.','art'=>'ocean','treatment'=>'coastal','font'=>'segoe-ui','radius'=>24,'button'=>'pill'),
        'forest'=>array('description'=>'Immersive woodland, natural light and quiet organic detail.','art'=>'forest','treatment'=>'botanical','font'=>'georgia','radius'=>18,'button'=>'rounded'),
        'christmas'=>array('name'=>'Christmas','description'=>'Evergreen, hanging ornaments and warm winter lights.','art'=>'christmas','treatment'=>'festive','font'=>'georgia','radius'=>16,'button'=>'rounded','colors'=>array('#062822','#123c32','#fff5df','#c5d9cb','#ecc777','#658370')),
        'halloween'=>array('name'=>'Halloween','description'=>'Moonlit branches, amber pumpkins and dramatic framed panels.','art'=>'halloween','treatment'=>'haunted','font'=>'georgia','radius'=>3,'button'=>'square','colors'=>array('#0d1028','#242039','#fff2de','#c8bbd4','#ffbc72','#65517b')),
        'easter'=>array('name'=>'Easter','description'=>'Decorated pastel eggs, a porcelain hare and a luminous spring conservatory.','art'=>'easter','treatment'=>'easter','font'=>'georgia','radius'=>24,'button'=>'pill','colors'=>array('#f5edf3','#fffaf5','#463b54','#796b82','#87548a','#d9c5d8')),
        'spring'=>array('name'=>'Spring','description'=>'Botanical pastels, soft petal shapes and a light welcome.','art'=>'spring','treatment'=>'spring','font'=>'trebuchet-ms','radius'=>30,'button'=>'pill','colors'=>array('#ecf2e9','#fffaf6','#344943','#63766a','#8d4655','#b1c6b3')),
        'summer'=>array('name'=>'Summer / Beach','description'=>'Sun, rolling surf, sand and relaxed resort cards.','art'=>'summer','treatment'=>'sunny','font'=>'trebuchet-ms','radius'=>22,'button'=>'pill','colors'=>array('#daf0ed','#fff9ed','#154a51','#476d70','#9b451e','#98c5c4')),
        'autumn'=>array('name'=>'Autumn','description'=>'Copper leaves, warm editorial panels and rich harvest tones.','art'=>'autumn','treatment'=>'harvest','font'=>'georgia','radius'=>7,'button'=>'rounded','colors'=>array('#211e26','#38302d','#fff2db','#d1b9a0','#eeb47a','#88624a')),
        'community'=>array('name'=>'Community','description'=>'A welcoming town square, rounded cards and inviting teal.','art'=>'community','treatment'=>'friendly','font'=>'segoe-ui','radius'=>28,'button'=>'pill','colors'=>array('#e2f0ef','#ffffff','#183f4a','#4b6e73','#126777','#a5c9ce')),
        'marketplace'=>array('name'=>'Marketplace / Shop','description'=>'A luminous boutique gallery, catalogue cards and crisp calls to action.','art'=>'marketplace','treatment'=>'editorial','font'=>'georgia','radius'=>4,'button'=>'square','colors'=>array('#f3e7d9','#fffbf5','#46362d','#7d6350','#994720','#cbb092')),
        'fantasy'=>array('name'=>'Fantasy / Roleplay','description'=>'A starlit landscape, distant towers and immersive storybook type.','art'=>'fantasy','treatment'=>'fantasy','font'=>'palatino','radius'=>8,'button'=>'rounded','colors'=>array('#10162f','#202a49','#f0edff','#b8bedb','#b2c9ff','#5b689d')),
        'festival'=>array('name'=>'Events / Festival','description'=>'A dimensional stage, colorful beams and bold poster-inspired sections.','art'=>'festival','treatment'=>'festival','font'=>'trebuchet-ms','radius'=>18,'button'=>'pill','colors'=>array('#101d3c','#29234c','#fff0fc','#d1b8df','#ffb0da','#775c9c')),
        'modern-dark'=>array('name'=>'Modern Dark','description'=>'Sculpted graphite and glass, precise type and sharply defined cards.','art'=>'abstract','treatment'=>'modern','font'=>'segoe-ui','radius'=>10,'button'=>'square','colors'=>array('#101d33','#1a2c46','#eef5ff','#abbfd5','#a0c4ff','#49627e')),
        'modern-light'=>array('name'=>'Modern Light','description'=>'Ivory architectural depth, open spacing and refined surfaces.','art'=>'minimal','treatment'=>'minimal','font'=>'segoe-ui','radius'=>2,'button'=>'square','colors'=>array('#f3f1eb','#ffffff','#292f35','#66706d','#394f69','#bcc6c6')));
}
function ag_sd_extend_presets($presets) {
    foreach(ag_sd_theme_content() as $id=>$content){
        $theme=$presets[$id] ?? array('name'=>$content['name'],'font'=>$content['font'],'colors'=>array_combine(array('background','surface','text','muted','accent','border'),$content['colors']));
        $theme['font']=$content['font'];$theme['styles']=array_merge(ag_sd_style_defaults(),array('treatment'=>$content['treatment'],'artwork'=>$content['art'],'radius'=>$content['radius'],'button'=>$content['button']));$presets[$id]=$theme;
    }return $presets;
}
function ag_sd_design_css($styles,$scope='public') {
    $s=ag_sd_styles($styles);$dark=in_array($s['treatment'],array('classic','coastal','botanical','festive','haunted','harvest','fantasy','festival','modern'),true);
    $t=$s['treatment'];$shadow=in_array($t,array('coastal','fantasy','festival'),true)?'0 18px 60px rgba(0,0,0,.28)':'0 12px 30px rgba(0,0,0,.10)';
    $css='--site-card-shadow:'.$shadow.';--site-hero-spacing:'.($scope==='admin'?'28':'64').'px;--site-hero-letter-spacing:'.(in_array($t,array('classic','haunted','fantasy'),true)?'.02em':'-.035em').';';
    $css.='--site-panel-treatment:'.($s['panel']==='outlined'?'var(--site-background)':($scope==='admin'?'var(--site-surface)':($dark?'linear-gradient(145deg,color-mix(in srgb,var(--site-surface) 94%,white),color-mix(in srgb,var(--site-surface) 96%,transparent))':'var(--site-surface)'))).';';
    $css.='--site-hero-rule:'.(in_array($t,array('classic','editorial','harvest'),true)?'3px solid var(--site-accent)':'0 solid transparent').';';
    $art=$s['artwork'];if($art!==''&&$s['background']===''){$a=ag_sd_artwork_library()[$art];if(is_file($a['path']))$css.='--site-background-image:linear-gradient('.($scope==='admin'?'rgba(0,0,0,.65),rgba(0,0,0,.65)':($dark?'rgba(0,0,0,.12),rgba(0,0,0,.18)':'rgba(255,255,255,.12),rgba(255,255,255,.12)')).'),url("'.$a['url'].'");';}
    return $css;
}
function ag_sd_visual_card($theme,$title,$scope='public',$layout='') {
    $t=ag_sa_theme(empty($theme['colors'])?ag_sa_presets()['classic-gold']:$theme);if(empty($theme['colors']))$t['styles']=ag_sd_style_defaults();$s=$t['styles'];$art=ag_sd_artwork_library()[$s['artwork']] ?? null;$bg=$s['background']?ag_sd_asset_url($s['background']):($art['url'] ?? '');$font=ag_pd_font_catalog()[$t['font']]['css'];
    $style=implode(';',array_map(function($key,$value){return '--site-'.$key.':'.$value;},array_keys($t['colors']),array_values($t['colors']))).';'.ag_sd_style_css($s).ag_sd_design_css($s,$scope).';font-family:'.$font;
    return '<div class="design-mini" data-treatment="'.ag_pd_h($s['treatment']).'" data-layout="'.ag_pd_h(isset(ag_sd_starters()[$layout])?$layout:'').'" style="'.ag_pd_h($style).'">'.($bg?'<img class="mini-art" loading="lazy" src="'.ag_pd_h($bg).'" alt="">':'').'<div class="mini-heading"><small>EXPLORE · CONNECT · CREATE</small><strong>'.ag_pd_h($title).'</strong><span>A world of possibilities</span></div><div class="mini-panel"><span>Member Login</span><i></i><i></i><b>Welcome in</b></div><div class="mini-tiles"><span></span><span></span><span></span></div></div>';
}
function ag_sd_apply_artwork($art,$upload,$target,$revision) {
    if($art!==''&&!isset(ag_sd_artwork_library()[$art]))throw new RuntimeException('Choose built-in artwork.');$upload=ag_sd_asset_name($upload);if($upload!==''&&!ag_sd_asset_path($upload))throw new RuntimeException('Uploaded artwork is missing.');
    if(!in_array($target,array('public','admin','user','designer','current-theme'),true))throw new RuntimeException('Choose an artwork destination.');
    return ag_sa_change($revision,function($s)use($art,$upload,$target){$scopes=$target==='current-theme'?array_keys(array_filter($s['scopes'],function($id)use($s){return $id===$s['scopes']['public'];})):array($target);foreach($scopes as $scope){if(count($s['themes'])>=50)throw new RuntimeException('Remove an unused saved theme first.');$theme=ag_sd_active_theme($s,$scope);if(empty($theme['colors']))$theme=ag_sa_presets()['classic-gold'];$theme=ag_sa_theme($theme);$defaultArt=$art;if($art===''&&$upload==='')foreach(ag_sd_theme_content() as $content)if($content['treatment']===$theme['styles']['treatment']){$defaultArt=$content['art'];break;}$theme['styles']['artwork']=$defaultArt;$theme['styles']['background']=$upload;$theme['name']=ag_pd_text($theme['name'].' artwork',80);$id=bin2hex(random_bytes(8));$s['themes'][$id]=$theme;$s['scopes'][$scope]=$id;$s['activeThemes'][$scope]=$theme;}return $s;},array('label'=>$art===''&&$upload===''?'Restore theme artwork default':'Apply artwork','scopes'=>$target==='current-theme'?array_keys(ag_sd_scopes()):array($target)));
}
