<?php
function ag_sd_starters() {
    return array(
      'classic-gold'=>array('name'=>'Classic Gold','theme'=>'classic-gold','heading'=>'A world of possibilities','text'=>'An elegant split welcome with a dedicated member panel.','cards'=>array('Explore','Connect','Create')),
      'community'=>array('name'=>'Community Grid','theme'=>'community','heading'=>'Find your people. Make your place.','text'=>'A welcoming hero, conversation cards and a friendly sign-in area.','cards'=>array('Meet residents','Build together','Discover places')),
      'marketplace'=>array('name'=>'Shop / Marketplace','theme'=>'marketplace','heading'=>'Made with imagination. Shared with you.','text'=>'A storefront hero, creator categories and a clear member invitation.','cards'=>array('Art & design','Homes & places','Fashion & style')),
      'roleplay'=>array('name'=>'Roleplay / Fantasy','theme'=>'fantasy','heading'=>'Every world begins with a story.','text'=>'A cinematic storybook welcome with an atmospheric member panel.','cards'=>array('The world','Your story')),
      'events'=>array('name'=>'Events Grid','theme'=>'festival','heading'=>'Good company. Great moments.','text'=>'A festival banner, event-format cards and a bold invitation.','cards'=>array('Music & performance','Meetups & workshops','Community celebrations')),
      'minimal'=>array('name'=>'Minimal / Modern','theme'=>'modern-light','heading'=>'Your next chapter.','text'=>'A centred login with quiet typography and open space.','cards'=>array()),
      'christmas'=>array('name'=>'Christmas','theme'=>'christmas','heading'=>'A little wonder. A warm welcome.','text'=>'Evergreen artwork, winter lights and seasonal community panels.','cards'=>array('Gather together','Share the season','Explore winter worlds')),
      'easter'=>array('name'=>'Easter','theme'=>'easter','heading'=>'Fresh beginnings. Shared joy.','text'=>'Pastel eggs, porcelain details and a welcoming Easter gathering.','cards'=>array('A fresh beginning','Little moments of joy')),
      'halloween'=>array('name'=>'Halloween','theme'=>'halloween','heading'=>'Step into the extraordinary.','text'=>'A moonlit full-width hero and a dramatic amber member panel.','cards'=>array('After dark','Unexpected adventures')));
}
function ag_sd_starter_page($id) {
    $s=ag_sd_starters()[$id] ?? null;if(!$s)throw new RuntimeException('Starter design not found.');
    $n=function($type,$props=array(),$style=array(),$children=array()){return array('id'=>bin2hex(random_bytes(6)),'type'=>$type,'name'=>ucwords(str_replace('-',' ',$type)),'props'=>$props,'style'=>$style,'children'=>$children);};
    $section=function($children,$style=array())use($n){return $n('section',array(),array_merge(array('padding'=>32,'gap'=>22),$style),$children);};
    $columns=function($children,$count=2)use($n){return $n('columns',array(),array('columns'=>$count,'mobileColumns'=>1,'gap'=>30),$children);};
    $preset=ag_sa_presets()[$s['theme']];$theme=$preset['colors'];$theme['font']=$preset['font'];$theme['radius']=$preset['styles']['radius'];$theme['width']=1200;
    $kickers=array('classic-gold'=>'EXPLORE. CONNECT. CREATE.','community'=>'A PLACE TO BELONG','marketplace'=>'CREATIVITY, CURATED','roleplay'=>'ENTER A WORLD OF STORIES','events'=>'MAKE THE MOMENT','minimal'=>'YOUR WORLD, SIMPLIFIED','easter'=>'A LITTLE EASTER WONDER','christmas'=>'A SEASON OF CONNECTION','halloween'=>'AFTER DARK, THE STORY BEGINS');
    $title=$n('heading',array('text'=>$s['heading'],'tag'=>'h1'),array('fontSize'=>$id==='minimal'?56:($id==='roleplay'?68:54),'font'=>$preset['font']));
    $welcome=$n('text',array('text'=>'A place to explore, connect and create.','designBinding'=>'welcomeText'),array('fontSize'=>19));
    $kicker=$n('text',array('text'=>$kickers[$id]),array('fontSize'=>13,'color'=>'accent','bold'=>true));
    $login=$n('grid-login',array(),array('padding'=>30,'background'=>'surface','radius'=>$preset['styles']['radius'],'shadow'=>'strong','width'=>'narrow'));
    $intro=$section(array($kicker,$title,$welcome),array('padding'=>40,'gap'=>24,'minHeight'=>340,'background'=>'surface','radius'=>$preset['styles']['radius'],'shadow'=>'soft'));
    $descriptions=array(
      'classic-gold'=>array('Discover inspiring places and find a world that feels like yours.','Good company starts with a conversation. Meet, share and belong.','Turn an idea into a place, a story or something entirely new.'),
      'community'=>array('Find familiar faces, share interests and welcome someone new.','Make room for big ideas and small moments worth sharing.','Explore the places our community brings to life.'),
      'marketplace'=>array('Discover expressive work, thoughtful detail and original ideas.','Find the spaces and objects that make a place feel like home.','Explore personal expression, from everyday style to the unexpected.'),
      'roleplay'=>array('A landscape of possibility. Choose a path and see where it leads.','Bring your imagination. Every new arrival adds another chapter.'),
      'events'=>array('Share the atmosphere of music, performance and a memorable evening.','Gather around a shared interest and make new connections.','Celebrate the places, people and ideas that bring a world to life.'),
      'christmas'=>array('Make time for good company and a warm welcome.','A thoughtful gesture. A new connection. A little unexpected joy.','Find winter scenery and make a memory of your own.'),
      'easter'=>array('Make room for a new idea, a new connection and a fresh adventure.','Explore together and share something that brightens the day.'),
      'halloween'=>array('Follow the lanterns into atmospheric places and unexpected stories.','Step beyond the familiar. Bring your curiosity and imagination.'));
    $cards=array();foreach($s['cards'] as $index=>$text){$children=array($n('text',array('text'=>str_pad((string)($index+1),2,'0',STR_PAD_LEFT)),array('color'=>'accent','fontSize'=>13,'bold'=>true)),$n('heading',array('text'=>$text,'tag'=>'h3'),array('fontSize'=>25)),$n('text',array('text'=>$descriptions[$id][$index]),array('fontSize'=>16)));$cards[]=$section($children,array('padding'=>30,'background'=>'surface','radius'=>$preset['styles']['radius'],'shadow'=>'soft','borderWidth'=>1,'borderColor'=>'accent'));}
    $blocks=array($n('site-branding',array(),array('padding'=>26)));
    if($id==='classic-gold'){$blocks[]=$section(array($columns(array($intro,$login))),array('paddingY'=>64));$blocks[]=$section(array($columns($cards,3)),array('paddingY'=>28));}
    elseif($id==='community'){$blocks[]=$section(array($kicker,$title,$welcome),array('align'=>'center','padding'=>42,'paddingY'=>54,'background'=>'surface','radius'=>28));$blocks[]=$section(array($columns(array($login,$section(array($n('heading',array('text'=>'Make yourself at home','tag'=>'h2'),array('fontSize'=>38)),$n('text',array('text'=>'There is room here for your interests, your ideas and your next adventure.'),array('fontSize'=>19)),$n('button',array('label'=>'Create an account','url'=>'/Other/index.php?panel=create-account'),array('background'=>'accent','color'=>'white','padding'=>16,'radius'=>28))),array('padding'=>36,'background'=>'surface','radius'=>28))))),array('paddingY'=>54));$blocks[]=$section(array($columns($cards,3)));}
    elseif($id==='marketplace'){$blocks[]=$section(array($intro),array('width'=>'narrow','align'=>'left','paddingY'=>56));$blocks[]=$section(array($n('heading',array('text'=>'Find your next inspiration','tag'=>'h2'),array('fontSize'=>34)),$columns($cards,3)),array('paddingY'=>32,'background'=>'surface','radius'=>4));$blocks[]=$section(array($columns(array($section(array($n('heading',array('text'=>'Your place in the creative community','tag'=>'h2'),array('fontSize'=>36)),$n('text',array('text'=>'Explore new ideas, connect with makers and make something of your own.'))),array('background'=>'surface','padding'=>38)),$login))),array('paddingY'=>66));}
    elseif($id==='roleplay'){$blocks[]=$section(array($kicker,$title,$welcome),array('width'=>'wide','align'=>'center','paddingY'=>90,'minHeight'=>410,'background'=>'surface','radius'=>8));$blocks[]=$section(array($columns(array($login,$section($cards,array('padding'=>0,'gap'=>28))))),array('paddingY'=>54));}
    elseif($id==='events'){$blocks[]=$section(array($kicker,$title,$welcome),array('padding'=>48,'paddingY'=>74,'background'=>'surface','borderWidth'=>3,'borderColor'=>'accent','radius'=>18));$blocks[]=$section(array($columns($cards,3)),array('paddingY'=>40));$blocks[]=$section(array($n('heading',array('text'=>'Be part of the moment','tag'=>'h2'),array('align'=>'center','fontSize'=>38)),$login),array('width'=>'narrow','paddingY'=>38,'background'=>'surface','radius'=>18));}
    elseif($id==='minimal'){$blocks[]=$section(array($kicker,$title,$welcome,$login),array('width'=>'narrow','align'=>'center','padding'=>36,'paddingY'=>74,'gap'=>28,'background'=>'surface','radius'=>2));}
    elseif($id==='christmas'){$blocks[]=$section(array($columns(array($section(array($kicker,$title,$welcome,$login),array('padding'=>34,'background'=>'surface','radius'=>16)),$section(array($n('heading',array('text'=>'Welcome, wherever you call home.','tag'=>'h2'),array('fontSize'=>40)),$n('text',array('text'=>'Share a little joy and make a new memory.'),array('fontSize'=>20)),$cards[0],$cards[1],$cards[2]),array('padding'=>28,'background'=>'surface','radius'=>16))))),array('paddingY'=>66));}
    elseif($id==='easter'){$blocks[]=$section(array($kicker,$title,$welcome),array('align'=>'center','padding'=>38,'paddingY'=>56,'background'=>'surface','radius'=>24));$blocks[]=$section(array($columns(array($cards[0],$login,$cards[1]),3)),array('paddingY'=>52));}
    elseif($id==='halloween'){$blocks[]=$section(array($columns(array($intro,$section(array($n('text',array('text'=>'YOUR INVITATION AWAITS'),array('color'=>'accent','bold'=>true,'fontSize'=>13)),$login),array('padding'=>28,'background'=>'surface','borderWidth'=>2,'borderColor'=>'accent','radius'=>3))))),array('paddingY'=>92,'minHeight'=>560));$blocks[]=$section(array($columns($cards,2)),array('paddingY'=>32));}
    $blocks[]=$section(array($n('text',array('text'=>'Login address','designBinding'=>'loginAddress'),array('fontSize'=>14)),$n('text',array('text'=>'Welcome to our community.','designBinding'=>'footer'))),array('align'=>'center','paddingY'=>28,'background'=>'surface','radius'=>$preset['styles']['radius']));
    $p=ag_pd_default_page();$p['title']=$s['name'].' welcome';$p['slug']=ag_pd_slug($p['title']);$p['builder']=array('theme'=>$theme,'blocks'=>$blocks);return ag_pd_normalize($p);
}
function ag_sd_create_starter($id,$name='') {
    $p=ag_sd_starter_page($id);if(is_string($name)&&trim($name)!==''){$p['title']=ag_pd_text($name,120);$p['slug']=ag_pd_slug($name);}
    $art=ag_sa_presets()[ag_sd_starters()[$id]['theme']]['styles']['artwork'];$asset=ag_sd_artwork_library()[$art];$bytes=file_get_contents($asset['path']);ag_sd_image($bytes);$image=bin2hex(random_bytes(12)).'.png';$p['builder']['theme']['backgroundImage']=$image;
    return ag_pd_import_package(json_encode(array('format'=>'dreamgrid-page','version'=>1,'page'=>$p,'assets'=>array($image=>array('data'=>base64_encode($bytes),'sha256'=>hash('sha256',$bytes)))),JSON_UNESCAPED_SLASHES));
}
