<?php
require_once __DIR__.'/../core/website-runtime.php';
// Validates avatar+password against the Robust DB (same UserAccounts/auth join and
// md5(md5(password):salt) check as GetAvatarLoginLevel in Modules/Mysql.vb) and, on
// success, sets a cookie so other pages under /API can read who is logged in without
// re-sending the password. config.php is generated by DreamGrid's DoPhpDbSetup() and
// is kept in sync with Settings.RobustMysqlConnection, so it's safe to trust as the
// DB connection source of truth.
require_once __DIR__ . '/../core/request-security.php';
ag_require_same_origin_post();
require_once __DIR__ . '/secret.php';
require_once __DIR__ . '/throttle.php';
header('Content-Type: text/plain');
header('Cache-Control: no-store');

$avatar = is_string($_POST['avatar'] ?? null) ? trim($_POST['avatar']) : '';
$password = is_string($_POST['password'] ?? null) ? $_POST['password'] : '';
if (strlen($avatar) > 512 || strlen($password) > 4096) {
    echo 'NAK You do not have permission to Log In';
    exit;
}

try {
    $secret = dreamGridSessionSecret();
    $throttleFile = __DIR__ . '/../private/login-throttle/state.json';
    $throttleKeys = dreamGridThrottleKeys($avatar, (string)($_SERVER['REMOTE_ADDR'] ?? ''), $secret);
    $retry = dreamGridThrottleBegin($throttleFile, $throttleKeys, time());
    if ($retry > 0) {
        http_response_code(429);
        header('Retry-After: ' . $retry);
        echo 'NAK You do not have permission to Log In';
        exit;
    }
} catch (Throwable $error) {
    http_response_code(503);
    echo 'NAK You do not have permission to Log In';
    exit;
}

require_once __DIR__ . '/../../MetroMap/includes/config.php';

$parts = preg_split('/\s+/', $avatar, 2);
$firstName = $parts[0] ?? '';
$lastName = $parts[1] ?? '';

if ($firstName === '' || $lastName === '') {
    echo 'NAK You do not have permission to Log In';
    exit;
}

$con = null;
$stmt = null;
try {
    $con = @mysqli_connect($CONF_db_server, $CONF_db_user, $CONF_db_pass, $CONF_db_database, (int) $CONF_db_port);
    if (!$con) throw new RuntimeException('Authentication unavailable');
    $stmt = mysqli_prepare($con, 'SELECT ua.UserLevel, ua.PrincipalID, a.passwordHash, a.passwordSalt
FROM UserAccounts ua
INNER JOIN auth a ON ua.PrincipalID = a.UUID
WHERE ua.FirstName = ? AND ua.LastName = ?');
    if (!$stmt) throw new RuntimeException('Authentication unavailable');
    mysqli_stmt_bind_param($stmt, 'ss', $firstName, $lastName);
    mysqli_stmt_execute($stmt);
    mysqli_stmt_bind_result($stmt, $userLevel, $principalId, $passwordHash, $passwordSalt);
    $found = mysqli_stmt_fetch($stmt);
} catch (Throwable $error) {
    http_response_code(503);
    echo 'NAK You do not have permission to Log In';
    exit;
} finally {
    if ($stmt) mysqli_stmt_close($stmt);
    if ($con) mysqli_close($con);
}

if (!$found) {
    echo 'NAK You do not have permission to Log In';
    exit;
}

// Same two-stage MD5 as GetMD5 in Modules/Mysql.vb: md5(password) then md5("{that}:{salt}")
$hashed = md5(md5($password) . ':' . $passwordSalt);

if (!hash_equals((string)$passwordHash, $hashed) || $userLevel < 0) {
    echo 'NAK You do not have permission to Log In';
    exit;
}

$issuedAt = time();
$session = [
    'issuedAt' => $issuedAt,
    'expiresAt' => $issuedAt + 8 * 3600,
    'avatar' => "$firstName $lastName",
    'principalId' => $principalId,
    'level' => (int) $userLevel,
];

// Cookie is the session's own trust boundary: signed with a server-side secret so a
// client can't forge a higher UserLevel by editing the cookie value directly.
try {
    dreamGridThrottleSuccess($throttleFile, $throttleKeys);
} catch (Throwable $error) {
    http_response_code(503);
    echo 'NAK You do not have permission to Log In';
    exit;
}
$payload = base64_encode(json_encode($session));
$signature = hash_hmac('sha256', $payload, $secret);
setcookie('dg_session', "$payload.$signature", [
    'expires' => $session['expiresAt'],
    'path' => '/Other/',
    'httponly' => true,
    'secure' => ag_web_secure_request(),
    'samesite' => 'Lax',
]);

echo 'Success';

